@startuml
class "internal::dense_map_node<Key,Type>" as C_0001949040226502523653
class C_0001949040226502523653 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L31{dense_map_node}]] {
+dense_map_node<Key, Type><Args...>(const std::size_t pos, Args &&... args) : void
+dense_map_node<Key, Type><Allocator,Args...>(std::allocator_arg_t, const Allocator & allocator, const std::size_t pos, Args &&... args) : void
+dense_map_node<Key, Type><Allocator>(std::allocator_arg_t, const Allocator & allocator, const dense_map_node<Key,Type> & other) : void
+dense_map_node<Key, Type><Allocator>(std::allocator_arg_t, const Allocator & allocator, dense_map_node<Key,Type> && other) : void
__
+element : internal::dense_map_node::value_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L55{element}]]]
+next : std::size_t [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L54{next}]]]
}
class "internal::dense_map_iterator<Other>" as C_0001376588142308052157
class C_0001376588142308052157 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L59{dense_map_iterator}]] {
__
}
class "internal::dense_map_iterator<It>" as C_0000861079117123945586
class C_0000861079117123945586 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L59{dense_map_iterator}]] {
+dense_map_iterator() noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L73{dense_map_iterator}]]]
+dense_map_iterator(const It iter) noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L76{dense_map_iterator}]]]
+dense_map_iterator<It><Other,typename=std::enable_if_t<!std::is_same_v<It, Other> && std::is_constructible_v<It, Other> >>(const dense_map_iterator<Other> & other) noexcept : void
..
+operator*() constexpr const noexcept : internal::dense_map_iterator::reference [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L127{operator*}]]]
+operator+(const internal::dense_map_iterator::difference_type value) constexpr const noexcept : dense_map_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L106{operator+}]]]
+operator++() constexpr noexcept : dense_map_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L83{operator++}]]]
+operator++(int) constexpr noexcept : dense_map_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L87{operator++}]]]
+operator+=(const internal::dense_map_iterator::difference_type value) constexpr noexcept : dense_map_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L101{operator+=}]]]
+operator-(const internal::dense_map_iterator::difference_type value) constexpr const noexcept : dense_map_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L115{operator-}]]]
+operator--() constexpr noexcept : dense_map_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L92{operator--}]]]
+operator--(int) constexpr noexcept : dense_map_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L96{operator--}]]]
+operator-=(const internal::dense_map_iterator::difference_type value) constexpr noexcept : dense_map_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L111{operator-=}]]]
+operator->() constexpr const noexcept : internal::dense_map_iterator::pointer [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L123{operator->}]]]
+operator[](const internal::dense_map_iterator::difference_type value) constexpr const noexcept : internal::dense_map_iterator::reference [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L119{operator[]}]]]
__
-it : It [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L141{it}]]]
}
class "internal::dense_map_local_iterator<Other>" as C_0000897312785691592656
class C_0000897312785691592656 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L180{dense_map_local_iterator}]] {
__
}
class "internal::dense_map_local_iterator<It>" as C_0002151284549161307803
class C_0002151284549161307803 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L180{dense_map_local_iterator}]] {
+dense_map_local_iterator() noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L194{dense_map_local_iterator}]]]
+dense_map_local_iterator(It iter, const std::size_t pos) noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L198{dense_map_local_iterator}]]]
+dense_map_local_iterator<It><Other,typename=std::enable_if_t<!std::is_same_v<It, Other> && std::is_constructible_v<It, Other> >>(const dense_map_local_iterator<Other> & other) noexcept : void
..
+operator*() constexpr const noexcept : internal::dense_map_local_iterator::reference [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L220{operator*}]]]
+operator++() constexpr noexcept : dense_map_local_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L207{operator++}]]]
+operator++(int) constexpr noexcept : dense_map_local_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L211{operator++}]]]
+operator->() constexpr const noexcept : internal::dense_map_local_iterator::pointer [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L216{operator->}]]]
..
+index() constexpr const noexcept : std::size_t [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L224{index}]]]
__
-it : It [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L229{it}]]]
-offset : std::size_t [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L230{offset}]]]
}
class "internal::dense_map_iterator<typename packed_container_type::const_iterator>" as C_0001653959084428336991
class C_0001653959084428336991 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L59{dense_map_iterator}]] {
__
}
class "internal::dense_map_iterator<typename packed_container_type::iterator>" as C_0001467357144574951784
class C_0001467357144574951784 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L59{dense_map_iterator}]] {
__
}
class "internal::dense_map_local_iterator<typename packed_container_type::const_iterator>" as C_0001059592200633017691
class C_0001059592200633017691 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L180{dense_map_local_iterator}]] {
__
}
class "internal::dense_map_local_iterator<typename packed_container_type::iterator>" as C_0001333101687401183603
class C_0001333101687401183603 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L180{dense_map_local_iterator}]] {
__
}
class "internal::dense_map_local_iterator<typename>" as C_0001638501202125067276
class C_0001638501202125067276 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L182{dense_map_local_iterator}]] {
__
}
class "internal::dense_map_iterator<typename>" as C_0002138822504316417237
class C_0002138822504316417237 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L61{dense_map_iterator}]] {
__
}
class "internal::dense_set_iterator<Other>" as C_0000049162385221685939
class C_0000049162385221685939 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L30{dense_set_iterator}]] {
__
}
class "internal::dense_set_iterator<It>" as C_0002029187173053297188
class C_0002029187173053297188 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L30{dense_set_iterator}]] {
+dense_set_iterator() noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L41{dense_set_iterator}]]]
+dense_set_iterator(const It iter) noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L44{dense_set_iterator}]]]
+dense_set_iterator<It><Other,typename=std::enable_if_t<!std::is_same_v<It, Other> && std::is_constructible_v<It, Other> >>(const dense_set_iterator<Other> & other) noexcept : void
..
+operator*() constexpr const noexcept : internal::dense_set_iterator::reference [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L95{operator*}]]]
+operator+(const internal::dense_set_iterator::difference_type value) constexpr const noexcept : dense_set_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L74{operator+}]]]
+operator++() constexpr noexcept : dense_set_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L51{operator++}]]]
+operator++(int) constexpr noexcept : dense_set_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L55{operator++}]]]
+operator+=(const internal::dense_set_iterator::difference_type value) constexpr noexcept : dense_set_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L69{operator+=}]]]
+operator-(const internal::dense_set_iterator::difference_type value) constexpr const noexcept : dense_set_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L83{operator-}]]]
+operator--() constexpr noexcept : dense_set_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L60{operator--}]]]
+operator--(int) constexpr noexcept : dense_set_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L64{operator--}]]]
+operator-=(const internal::dense_set_iterator::difference_type value) constexpr noexcept : dense_set_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L79{operator-=}]]]
+operator->() constexpr const noexcept : internal::dense_set_iterator::pointer [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L91{operator->}]]]
+operator[](const internal::dense_set_iterator::difference_type value) constexpr const noexcept : internal::dense_set_iterator::reference [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L87{operator[]}]]]
__
-it : It [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L109{it}]]]
}
class "internal::dense_set_local_iterator<Other>" as C_0000722665158129243283
class C_0000722665158129243283 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L148{dense_set_local_iterator}]] {
__
}
class "internal::dense_set_local_iterator<It>" as C_0001736854889005654369
class C_0001736854889005654369 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L148{dense_set_local_iterator}]] {
+dense_set_local_iterator() noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L159{dense_set_local_iterator}]]]
+dense_set_local_iterator(It iter, const std::size_t pos) noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L163{dense_set_local_iterator}]]]
+dense_set_local_iterator<It><Other,typename=std::enable_if_t<!std::is_same_v<It, Other> && std::is_constructible_v<It, Other> >>(const dense_set_local_iterator<Other> & other) noexcept : void
..
+operator*() constexpr const noexcept : internal::dense_set_local_iterator::reference [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L185{operator*}]]]
+operator++() constexpr noexcept : dense_set_local_iterator<It> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L172{operator++}]]]
+operator++(int) constexpr noexcept : dense_set_local_iterator<It> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L176{operator++}]]]
+operator->() constexpr const noexcept : internal::dense_set_local_iterator::pointer [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L181{operator->}]]]
..
+index() constexpr const noexcept : std::size_t [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L189{index}]]]
__
-it : It [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L194{it}]]]
-offset : std::size_t [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L195{offset}]]]
}
class "internal::dense_set_iterator<typename packed_container_type::const_iterator>" as C_0000560377495148252911
class C_0000560377495148252911 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L30{dense_set_iterator}]] {
__
}
class "internal::dense_set_iterator<typename packed_container_type::iterator>" as C_0000152036747823538986
class C_0000152036747823538986 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L30{dense_set_iterator}]] {
__
}
class "internal::dense_set_local_iterator<typename packed_container_type::const_iterator>" as C_0000412176680063565687
class C_0000412176680063565687 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L148{dense_set_local_iterator}]] {
__
}
class "internal::dense_set_local_iterator<typename packed_container_type::iterator>" as C_0001477017809704643123
class C_0001477017809704643123 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L148{dense_set_local_iterator}]] {
__
}
class "internal::dense_set_iterator<typename>" as C_0001565515217260524899
class C_0001565515217260524899 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L32{dense_set_iterator}]] {
__
}
class "internal::dense_set_local_iterator<typename>" as C_0001656541682645832012
class C_0001656541682645832012 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L150{dense_set_local_iterator}]] {
__
}
class "dense_map<Key,Type,Hash=std::hash<Key>,KeyEqual=std::equal_to<Key>,Allocator=std::allocator<std::pair<const Key, Type> >>" as C_0001073675684695097120
class C_0001073675684695097120 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L264{dense_map}]] {
+dense_map() : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L374{dense_map}]]]
+dense_map(const dense_map::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L381{dense_map}]]]
+dense_map(const dense_map::size_type cnt, const dense_map::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L390{dense_map}]]]
+dense_map(const dense_map::size_type cnt, const dense_map::hasher & hash, const dense_map::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L400{dense_map}]]]
+dense_map(const dense_map::size_type cnt, const dense_map::hasher & hash = hasher{}, const dense_map::key_equal & equal = key_equal{}, const dense_map::allocator_type & allocator = allocator_type{}) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L411{dense_map}]]]
+dense_map(const dense_map<Key,Type,type-parameter-0-2,type-parameter-0-3,type-parameter-0-4> &) = default : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L419{dense_map}]]]
+dense_map(const dense_map<Key,Type,type-parameter-0-2,type-parameter-0-3,type-parameter-0-4> & other, const dense_map::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L426{dense_map}]]]
+dense_map(dense_map<Key,Type,type-parameter-0-2,type-parameter-0-3,type-parameter-0-4> &&) noexcept = default : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L432{dense_map}]]]
+dense_map(dense_map<Key,Type,type-parameter-0-2,type-parameter-0-3,type-parameter-0-4> && other, const dense_map::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L439{dense_map}]]]
..
+operator=(const dense_map<Key,Type,type-parameter-0-2,type-parameter-0-3,type-parameter-0-4> &) = default : dense_map<Key,Type,type-parameter-0-2,type-parameter-0-3,type-parameter-0-4> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L448{operator=}]]]
+operator=(dense_map<Key,Type,type-parameter-0-2,type-parameter-0-3,type-parameter-0-4> &&) noexcept = default : dense_map<Key,Type,type-parameter-0-2,type-parameter-0-3,type-parameter-0-4> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L454{operator=}]]]
..
+operator[](const dense_map::key_type & key) : dense_map::mapped_type & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L738{operator[]}]]]
+operator[](dense_map::key_type && key) : dense_map::mapped_type & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L747{operator[]}]]]
..
+at(const dense_map::key_type & key) const : const dense_map::mapped_type & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L727{at}]]]
+at(const dense_map::key_type & key) : dense_map::mapped_type & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L720{at}]]]
+begin() const noexcept : dense_map::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L477{begin}]]]
+begin() noexcept : dense_map::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L482{begin}]]]
+begin(const dense_map::size_type index) : dense_map::local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L893{begin}]]]
+begin(const dense_map::size_type index) const : dense_map::const_local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L884{begin}]]]
+bucket(const dense_map::key_type & key) const : dense_map::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L954{bucket}]]]
+bucket_count() const : dense_map::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L928{bucket_count}]]]
+bucket_size(const dense_map::size_type index) const : dense_map::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L945{bucket_size}]]]
+cbegin(const dense_map::size_type index) const : dense_map::const_local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L875{cbegin}]]]
+cbegin() const noexcept : dense_map::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L472{cbegin}]]]
+cend(const dense_map::size_type index) const : dense_map::const_local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L902{cend}]]]
+cend() const noexcept : dense_map::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L496{cend}]]]
+clear() noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L535{clear}]]]
-constrained_find<Other>(const Other & key, std::size_t bucket) : auto
-constrained_find<Other>(const Other & key, std::size_t bucket) const : auto
+contains(const dense_map::key_type & key) const : bool [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L853{contains}]]]
+contains<Other>(const Other & key) const : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, _Bool> >
+count<Other>(const Other & key) const : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, size_type> >
+count(const dense_map::key_type & key) const : dense_map::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L756{count}]]]
+emplace<Args...>(Args &&... args) : std::pair<iterator, _Bool>
+empty() const noexcept : bool [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L514{empty}]]]
+end(const dense_map::size_type index) : dense_map::local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L920{end}]]]
+end(const dense_map::size_type index) const : dense_map::const_local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L911{end}]]]
+end() noexcept : dense_map::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L506{end}]]]
+end() const noexcept : dense_map::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L501{end}]]]
+equal_range(const dense_map::key_type & key) const : std::pair<const_iterator,const_iterator> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L820{equal_range}]]]
+equal_range(const dense_map::key_type & key) : std::pair<iterator,iterator> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L814{equal_range}]]]
+equal_range<Other>(const Other & key) const : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, std::pair<const_iterator, const_iterator> > >
+equal_range<Other>(const Other & key) : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, std::pair<iterator, iterator> > >
+erase(const dense_map::key_type & key) : dense_map::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L691{erase}]]]
+erase(dense_map::const_iterator first, dense_map::const_iterator last) : dense_map::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L676{erase}]]]
+erase(dense_map::const_iterator pos) : dense_map::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L664{erase}]]]
+find<Other>(const Other & key) : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, iterator> >
+find<Other>(const Other & key) const : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, const_iterator> >
+find(const dense_map::key_type & key) : dense_map::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L778{find}]]]
+find(const dense_map::key_type & key) const : dense_map::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L783{find}]]]
+get_allocator() constexpr const noexcept : dense_map::allocator_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L460{get_allocator}]]]
+hash_function() const : dense_map::hasher [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L1022{hash_function}]]]
+insert(const dense_map::value_type & value) : std::pair<iterator,bool> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L548{insert}]]]
+insert(dense_map::value_type && value) : std::pair<iterator,bool> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L553{insert}]]]
+insert<It>(It first, It last) : void
+insert<Arg>(Arg && value) : std::enable_if_t<std::is_constructible_v<value_type, Arg &&>, std::pair<iterator, _Bool> >
+insert_or_assign<Arg>(dense_map::key_type && key, Arg && value) : std::pair<iterator, _Bool>
+insert_or_assign<Arg>(const dense_map::key_type & key, Arg && value) : std::pair<iterator, _Bool>
-insert_or_do_nothing<Other,Args...>(Other && key, Args &&... args) : auto
-insert_or_overwrite<Other,Arg>(Other && key, Arg && value) : auto
+key_eq() const : dense_map::key_equal [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L1030{key_eq}]]]
-key_to_bucket<Other>(const Other & key) const noexcept : std::size_t
+load_factor() const : float [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L962{load_factor}]]]
+max_bucket_count() const : dense_map::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L936{max_bucket_count}]]]
+max_load_factor(const float value) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L978{max_load_factor}]]]
+max_load_factor() const : float [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L970{max_load_factor}]]]
+max_size() const noexcept : dense_map::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L530{max_size}]]]
-move_and_pop(const std::size_t pos) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L332{move_and_pop}]]]
+rehash(const dense_map::size_type cnt) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L989{rehash}]]]
-rehash_if_required() : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L343{rehash_if_required}]]]
+reserve(const dense_map::size_type cnt) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L1013{reserve}]]]
+size() const noexcept : dense_map::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L522{size}]]]
+swap(dense_map<Key,Type,type-parameter-0-2,type-parameter-0-3,type-parameter-0-4> & other) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L708{swap}]]]
+try_emplace<Args...>(const dense_map::key_type & key, Args &&... args) : std::pair<iterator, _Bool>
+try_emplace<Args...>(dense_map::key_type && key, Args &&... args) : std::pair<iterator, _Bool>
__
{static} -default_threshold : const float [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L265{default_threshold}]]]
{static} -minimum_capacity : const std::size_t [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L266{minimum_capacity}]]]
-packed : compressed_pair<dense_map::packed_container_type,dense_map::key_equal> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L1036{packed}]]]
-sparse : compressed_pair<dense_map::sparse_container_type,dense_map::hasher> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L1035{sparse}]]]
-threshold : float [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_map.hpp#L1037{threshold}]]]
}
class "dense_set<Type,typename=std::hash<Type>,typename=std::equal_to<Type>,typename=std::allocator<Type>>" as C_0002013462517635721608
class C_0002013462517635721608 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/fwd.hpp#L22{dense_set}]] {
__
}
class "dense_map<Key,Type,typename=std::hash<Key>,typename=std::equal_to<Key>,typename=std::allocator<std::pair<const Key, Type> >>" as C_0002133693157975512401
class C_0002133693157975512401 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/fwd.hpp#L15{dense_map}]] {
__
}
class "dense_set<Type,Hash=std::hash<Type>,KeyEqual=std::equal_to<Type>,Allocator=std::allocator<Type>>" as C_0001428356275870265271
class C_0001428356275870265271 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L228{dense_set}]] {
+dense_set() : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L320{dense_set}]]]
+dense_set(const dense_set::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L327{dense_set}]]]
+dense_set(const dense_set::size_type cnt, const dense_set::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L336{dense_set}]]]
+dense_set(const dense_set::size_type cnt, const dense_set::hasher & hash, const dense_set::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L346{dense_set}]]]
+dense_set(const dense_set::size_type cnt, const dense_set::hasher & hash = hasher{}, const dense_set::key_equal & equal = key_equal{}, const dense_set::allocator_type & allocator = allocator_type{}) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L357{dense_set}]]]
+dense_set(const dense_set<Type,type-parameter-0-1,type-parameter-0-2,type-parameter-0-3> &) = default : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L365{dense_set}]]]
+dense_set(const dense_set<Type,type-parameter-0-1,type-parameter-0-2,type-parameter-0-3> & other, const dense_set::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L372{dense_set}]]]
+dense_set(dense_set<Type,type-parameter-0-1,type-parameter-0-2,type-parameter-0-3> &&) noexcept = default : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L378{dense_set}]]]
+dense_set(dense_set<Type,type-parameter-0-1,type-parameter-0-2,type-parameter-0-3> && other, const dense_set::allocator_type & allocator) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L385{dense_set}]]]
..
+operator=(const dense_set<Type,type-parameter-0-1,type-parameter-0-2,type-parameter-0-3> &) = default : dense_set<Type,type-parameter-0-1,type-parameter-0-2,type-parameter-0-3> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L394{operator=}]]]
+operator=(dense_set<Type,type-parameter-0-1,type-parameter-0-2,type-parameter-0-3> &&) noexcept = default : dense_set<Type,type-parameter-0-1,type-parameter-0-2,type-parameter-0-3> & [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L400{operator=}]]]
..
+begin() const noexcept : dense_set::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L423{begin}]]]
+begin() noexcept : dense_set::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L428{begin}]]]
+begin(const dense_set::size_type index) : dense_set::local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L746{begin}]]]
+begin(const dense_set::size_type index) const : dense_set::const_local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L737{begin}]]]
+bucket(const dense_set::value_type & value) const : dense_set::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L807{bucket}]]]
+bucket_count() const : dense_set::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L781{bucket_count}]]]
+bucket_size(const dense_set::size_type index) const : dense_set::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L798{bucket_size}]]]
+cbegin() const noexcept : dense_set::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L418{cbegin}]]]
+cbegin(const dense_set::size_type index) const : dense_set::const_local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L728{cbegin}]]]
+cend() const noexcept : dense_set::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L442{cend}]]]
+cend(const dense_set::size_type index) const : dense_set::const_local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L755{cend}]]]
+clear() noexcept : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L481{clear}]]]
-constrained_find<Other>(const Other & value, std::size_t bucket) const : auto
-constrained_find<Other>(const Other & value, std::size_t bucket) : auto
+contains<Other>(const Other & value) const : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, _Bool> >
+contains(const dense_set::value_type & value) const : bool [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L706{contains}]]]
+count(const dense_set::value_type & key) const : dense_set::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L610{count}]]]
+count<Other>(const Other & key) const : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, size_type> >
+emplace<Args...>(Args &&... args) : std::pair<iterator, _Bool>
+empty() const noexcept : bool [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L460{empty}]]]
+end() const noexcept : dense_set::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L447{end}]]]
+end() noexcept : dense_set::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L452{end}]]]
+end(const dense_set::size_type index) : dense_set::local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L773{end}]]]
+end(const dense_set::size_type index) const : dense_set::const_local_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L764{end}]]]
+equal_range<Other>(const Other & value) const : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, std::pair<const_iterator, const_iterator> > >
+equal_range(const dense_set::value_type & value) : std::pair<iterator,iterator> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L667{equal_range}]]]
+equal_range(const dense_set::value_type & value) const : std::pair<const_iterator,const_iterator> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L673{equal_range}]]]
+equal_range<Other>(const Other & value) : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, std::pair<iterator, iterator> > >
+erase(const dense_set::value_type & value) : dense_set::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L581{erase}]]]
+erase(dense_set::const_iterator first, dense_set::const_iterator last) : dense_set::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L566{erase}]]]
+erase(dense_set::const_iterator pos) : dense_set::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L554{erase}]]]
+find<Other>(const Other & value) const : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, const_iterator> >
+find<Other>(const Other & value) : std::enable_if_t<is_transparent_v<hasher> && is_transparent_v<key_equal>, std::conditional_t<false, Other, iterator> >
+find(const dense_set::value_type & value) const : dense_set::const_iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L637{find}]]]
+find(const dense_set::value_type & value) : dense_set::iterator [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L632{find}]]]
+get_allocator() constexpr const noexcept : dense_set::allocator_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L406{get_allocator}]]]
+hash_function() const : dense_set::hasher [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L875{hash_function}]]]
+insert(const dense_set::value_type & value) : std::pair<iterator,bool> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L494{insert}]]]
+insert(dense_set::value_type && value) : std::pair<iterator,bool> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L499{insert}]]]
+insert<It>(It first, It last) : void
-insert_or_do_nothing<Other>(Other && value) : auto
+key_eq() const : dense_set::key_equal [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L883{key_eq}]]]
+load_factor() const : float [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L815{load_factor}]]]
+max_bucket_count() const : dense_set::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L789{max_bucket_count}]]]
+max_load_factor(const float value) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L831{max_load_factor}]]]
+max_load_factor() const : float [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L823{max_load_factor}]]]
+max_size() const noexcept : dense_set::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L476{max_size}]]]
-move_and_pop(const std::size_t pos) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L280{move_and_pop}]]]
+rehash(const dense_set::size_type cnt) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L842{rehash}]]]
-rehash_if_required() : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L291{rehash_if_required}]]]
+reserve(const dense_set::size_type cnt) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L866{reserve}]]]
+size() const noexcept : dense_set::size_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L468{size}]]]
+swap(dense_set<Type,type-parameter-0-1,type-parameter-0-2,type-parameter-0-3> & other) : void [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L598{swap}]]]
-value_to_bucket<Other>(const Other & value) const noexcept : std::size_t
__
{static} -default_threshold : const float [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L229{default_threshold}]]]
{static} -minimum_capacity : const std::size_t [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L230{minimum_capacity}]]]
-packed : compressed_pair<dense_set::packed_container_type,dense_set::key_equal> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L889{packed}]]]
-sparse : compressed_pair<dense_set::sparse_container_type,dense_set::hasher> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L888{sparse}]]]
-threshold : float [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/container/dense_set.hpp#L890{threshold}]]]
}
C_0001376588142308052157 ..|> C_0000861079117123945586
C_0000861079117123945586 ..> C_0001376588142308052157
C_0000897312785691592656 ..|> C_0002151284549161307803
C_0002151284549161307803 ..> C_0000897312785691592656
C_0001653959084428336991 ..|> C_0001376588142308052157
C_0001467357144574951784 ..|> C_0001376588142308052157
C_0001059592200633017691 ..|> C_0000897312785691592656
C_0001333101687401183603 ..|> C_0000897312785691592656
C_0000049162385221685939 ..|> C_0002029187173053297188
C_0002029187173053297188 ..> C_0000049162385221685939
C_0000722665158129243283 ..|> C_0001736854889005654369
C_0001736854889005654369 ..> C_0000722665158129243283
C_0000560377495148252911 ..|> C_0000049162385221685939
C_0000152036747823538986 ..|> C_0000049162385221685939
C_0000412176680063565687 ..|> C_0000722665158129243283
C_0001477017809704643123 ..|> C_0000722665158129243283
C_0001073675684695097120 ..> C_0001653959084428336991
C_0001073675684695097120 ..> C_0001467357144574951784
C_0001073675684695097120 ..> C_0001059592200633017691
C_0001073675684695097120 ..> C_0001333101687401183603
C_0001428356275870265271 ..> C_0000560377495148252911
C_0001428356275870265271 ..> C_0000152036747823538986
C_0001428356275870265271 ..> C_0000412176680063565687
C_0001428356275870265271 ..> C_0001477017809704643123

'Generated with clang-uml, version 0.3.7-36-g13ea67c
'LLVM version Ubuntu clang version 15.0.6
@enduml
