@startuml
class "locator<Service>" as C_0002057168254138054942
class C_0002057168254138054942 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/locator/locator.hpp#L27{locator}]] {
+locator() = deleted : void
+~locator() = deleted : void
..
{static} +allocate_emplace<Impl=Service,Allocator,Args...>(Allocator alloc, Args &&... args) : Service &
{static} +emplace<Impl=Service,Args...>(Args &&... args) : Service &
{static} +handle() noexcept : locator::node_type
{static} +has_value() noexcept : bool
{static} +reset(const locator::node_type & other = {}) noexcept : void
{static} +value() noexcept : Service &
{static} +value_or<Impl=Service,Args...>(Args &&... args) : Service &
__
{static} -service : std::shared_ptr<Service> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/locator/locator.hpp#L130{service}]]]
}
class "locator::service_handle" as C_0002252539691859806017
class C_0002252539691859806017 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/locator/locator.hpp#L28{locator##service_handle}]] {
__
-value : std::shared_ptr<Service> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/locator/locator.hpp#L30{value}]]]
}
C_0002252539691859806017 --+ C_0002057168254138054942

'Generated with clang-uml, version 0.3.6-29-g238bfb0
'LLVM version Ubuntu clang version 15.0.6
@enduml
