@startuml
class "basic_poly<Concept>" as C_0002187650141235109775
class C_0002187650141235109775 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/poly/fwd.hpp#L9{basic_poly}]] {
__
}
class "poly_inspector" as C_0000460891939233668905
class C_0000460891939233668905 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/poly/poly.hpp#L17{poly_inspector}]] {
+invoke<std::size_t Member,Args...>(Args &&... args) const : struct poly_inspector
+invoke<std::size_t Member,Args...>(Args &&... args) : struct poly_inspector
+operator type-parameter-0-0 &&<Type>() const : Type &&
__
}
class "poly_vtable<Concept,std::size_t Len,std::size_t Align>" as C_0000593699980024327418
class C_0000593699980024327418 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/poly/poly.hpp#L47{poly_vtable}]] {
{static} -fill_vtable<Type,auto... Index>(std::index_sequence<Index...>) noexcept : auto
{static} -fill_vtable_entry<Type,auto Candidate,Ret,Any,Args...>(Ret (*&)(Any &,Args...) entry) noexcept : void
{static} +instance<Type>() noexcept : poly_vtable::type
{static} -make_vtable<auto... Candidate>(value_list<Candidate...>) noexcept : decltype(std::make_tuple(vtable_entry(Candidate)...))
{static} -make_vtable<Func...>(type_list<Func...>) constexpr noexcept : auto
{static} -vtable_entry<Ret,Args...>(Ret (*)(poly_vtable::inspector &,Args...)) : Ret (*)(basic_any<Len, Align> &, Args...)
{static} -vtable_entry<Ret,Args...>(Ret (*)(const poly_vtable::inspector &,Args...)) : Ret (*)(const basic_any<Len, Align> &, Args...)
{static} -vtable_entry<Ret,Args...>(Ret (*)(Args...)) : Ret (*)(const basic_any<Len, Align> &, Args...)
{static} -vtable_entry<Ret,Args...>(Ret (poly_vtable::inspector::*)(Args...)) : Ret (*)(basic_any<Len, Align> &, Args...)
{static} -vtable_entry<Ret,Args...>(Ret (poly_vtable::inspector::*)(Args...) const) : Ret (*)(const basic_any<Len, Align> &, Args...)
__
{static} -is_mono_v : const bool [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/poly/poly.hpp#L99{is_mono_v}]]]
}
class "poly_base<Poly>" as C_0001758879837962625486
class C_0001758879837962625486 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/poly/poly.hpp#L128{poly_base}]] {
+invoke<std::size_t Member,Args...>(const poly_base<Poly> & self, Args &&... args) const : decltype(auto)
+invoke<std::size_t Member,Args...>(poly_base<Poly> & self, Args &&... args) : decltype(auto)
__
}
class "basic_poly<Concept,std::size_t Len=sizeof(double[2]),std::size_t Align=__alignof(double[2])>" as C_0002224173078316961772
class C_0002224173078316961772 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/poly/poly.hpp#L192{basic_poly}]] {
+basic_poly() noexcept : void
+basic_poly<type-parameter-0-0, Len, ><Type,Args...>(std::in_place_type_t<Type>, Args &&... args) : void
+basic_poly<type-parameter-0-0, Len, ><Type,typename=std::enable_if_t<!std::is_same_v<std::remove_cv_t<std::remove_reference_t<Type> >, basic_poly<type-parameter-0-0, Len, > > >>(Type && value) noexcept : void
..
+operator->() noexcept : basic_poly::concept_type *
+operator->() const noexcept : const basic_poly::concept_type *
..
+as_ref() noexcept : basic_poly<type-parameter-0-0,Len,>
+as_ref() const noexcept : basic_poly<type-parameter-0-0,Len,>
+data() const noexcept : const void *
+data() noexcept : void *
+emplace<Type,Args...>(Args &&... args) : void
+operator bool() const noexcept : bool
+reset() : void
+type() const noexcept : const type_info &
__
-storage : basic_any<Len,Align> [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/poly/poly.hpp#L307{storage}]]]
-vtable : basic_poly::vtable_type [[[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/poly/poly.hpp#L308{vtable}]]]
}
class "basic_poly<typename,std::size_t Len=sizeof(double[2]),std::size_t=__alignof(double[2])>" as C_0002054155751960602394
class C_0002054155751960602394 [[https://github.com/skypjack/entt/blob/fef921132cae7588213d0f9bcd2fb9c8ffd8b7fc/src/entt/poly/fwd.hpp#L9{basic_poly}]] {
__
}
C_0002187650141235109775 ..|> C_0002054155751960602394

'Generated with clang-uml, version 0.3.6-29-g238bfb0
'LLVM version Ubuntu clang version 15.0.6
@enduml
