@startuml
title App::MaterialObject context
package [Base] as C_0000701777446892506059 {
class "Type" as C_0001299587473968259399
class C_0001299587473968259399 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L80{Type}]] {
+Type(const Base::Type & type) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L84{Type}]]]
+Type() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L85{Type}]]]
+~Type() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L87{~Type}]]]
..
+operator=(const Base::Type type) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L114{operator=}]]]
..
+operator!=(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L116{operator!=}]]]
+operator<(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L118{operator<}]]]
+operator<=(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L119{operator<=}]]]
+operator==(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L115{operator==}]]]
+operator>(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L121{operator>}]]]
+operator>=(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L120{operator>=}]]]
..
{static} +badType() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L123{badType}]]]
+createInstance() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L90{createInstance}]]]
{static} +createInstanceByName(const char * TypeName, bool bLoadModule = false) : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L92{createInstanceByName}]]]
{static} +createType(const Base::Type parent, const char * name, Base::Type::instantiationMethod method = nullptr) : const Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L109{createType}]]]
{static} +destruct() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L125{destruct}]]]
{static} +fromKey(unsigned int key) : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L98{fromKey}]]]
{static} +fromName(const char * name) : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L97{fromName}]]]
{static} +getAllDerivedFrom(const Base::Type type, std::vector<Type> & List) : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L103{getAllDerivedFrom}]]]
+getKey() const : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L111{getKey}]]]
{static} #getModuleName(const char * ClassName) : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L128{getModuleName}]]]
+getName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L99{getName}]]]
{static} +getNumTypes() : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L107{getNumTypes}]]]
+getParent() const : const Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L100{getParent}]]]
{static} +getTypeIfDerivedFrom(const char * name, const Base::Type parent, bool bLoadModule = false) : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L105{getTypeIfDerivedFrom}]]]
{static} +importModule(const char * TypeName) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L93{importModule}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L124{init}]]]
+isBad() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L112{isBad}]]]
+isDerivedFrom(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L101{isDerivedFrom}]]]
__
-index : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L134{index}]]]
{static} -loadModuleSet : std::set<std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L140{loadModuleSet}]]]
{static} -typedata : std::vector<TypeData *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L138{typedata}]]]
{static} -typemap : std::map<std::string,unsigned int> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L137{typemap}]]]
}
}
package [App] as C_0002285326295477687690 {
class "PropertyData" as C_0001065140174462797402
class C_0001065140174462797402 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L56{PropertyData}]] {
+addProperty(App::PropertyData::OffsetBase offsetBase, const char * PropName, App::Property * Prop, const char * PropertyGroup = nullptr, App::PropertyType  = Prop_None, const char * PropertyDocu = nullptr) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L116{addProperty}]]]
+findProperty(App::PropertyData::OffsetBase offsetBase, const char * PropName) const : const App::PropertyData::PropertySpec * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L118{findProperty}]]]
+findProperty(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const App::PropertyData::PropertySpec * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L119{findProperty}]]]
+getDocumentation(App::PropertyData::OffsetBase offsetBase, const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L126{getDocumentation}]]]
+getDocumentation(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L127{getDocumentation}]]]
+getGroup(App::PropertyData::OffsetBase offsetBase, const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L124{getGroup}]]]
+getGroup(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L125{getGroup}]]]
+getName(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L121{getName}]]]
+getPropertyByName(App::PropertyData::OffsetBase offsetBase, const char * name) const : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L129{getPropertyByName}]]]
+getPropertyList(App::PropertyData::OffsetBase offsetBase, std::vector<Property *> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L131{getPropertyList}]]]
+getPropertyMap(App::PropertyData::OffsetBase offsetBase, std::map<std::string,Property *> & Map) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L130{getPropertyMap}]]]
+getPropertyNamedList(App::PropertyData::OffsetBase offsetBase, std::vector<std::pair<const char *,Property *>> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L132{getPropertyNamedList}]]]
+getType(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L122{getType}]]]
+getType(App::PropertyData::OffsetBase offsetBase, const char * name) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L123{getType}]]]
+merge(App::PropertyData * other = nullptr) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L134{merge}]]]
+split(App::PropertyData * other) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L135{split}]]]
__
+parentMerged : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L112{parentMerged}]]]
+parentPropertyData : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L114{parentPropertyData}]]]
+propertyData : bmi::multi_index_container<PropertySpec,bmi::indexed_by<bmi::sequenced<>,bmi::hashed_unique<bmi::member<PropertySpec,const char *,&PropertySpec::Name>,CStringHasher,CStringHasher>,bmi::hashed_unique<bmi::member<PropertySpec,short,&PropertySpec::Offset>>>> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L110{propertyData}]]]
}
class "PropertyMap" as C_0002237031220373524384
class C_0002237031220373524384 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L425{PropertyMap}]] {
+PropertyMap() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L435{PropertyMap}]]]
+~PropertyMap() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L441{~PropertyMap}]]]
..
+operator[](const std::string & key) const : const std::string & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L452{operator[]}]]]
..
+Copy() const : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L466{Copy}]]]
+Paste(const App::Property & from) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L467{Paste}]]]
+Restore(Base::XMLReader & reader) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L464{Restore}]]]
+Save(Base::Writer & writer) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L463{Save}]]]
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L427{create}]]]
{static} +getClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L427{getClassTypeId}]]]
+getMemSize() const : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L469{getMemSize}]]]
+getPyObject() : PyObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L460{getPyObject}]]]
+getSize() const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L443{getSize}]]]
+getTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L427{getTypeId}]]]
+getValues() const : const std::map<std::string,std::string> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L456{getValues}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L427{init}]]]
+isSame(const App::Property & other) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L471{isSame}]]]
+set1Value(const std::string & key, const std::string & value) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L454{set1Value}]]]
+setPyObject(PyObject *) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L461{setPyObject}]]]
+setValue(const std::string & key, const std::string & value) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L448{setValue}]]]
+setValue() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L447{setValue}]]]
+setValues(const std::map<std::string,std::string> &) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L449{setValues}]]]
__
-_lValueList : std::map<std::string,std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L479{_lValueList}]]]
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyStandard.h#L427{classTypeId}]]]
}
class "DocumentObject" as C_0001679842198945066576
class C_0001679842198945066576 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L96{DocumentObject}]] {
+DocumentObject() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L132{DocumentObject}]]]
+~DocumentObject() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L133{~DocumentObject}]]]
..
+Save(Base::Writer & writer) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L427{Save}]]]
+_addBackLink(App::DocumentObject *) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L274{_addBackLink}]]]
+_removeBackLink(App::DocumentObject *) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L272{_removeBackLink}]]]
+addDynamicProperty(const char * type, const char * name = nullptr, const char * group = nullptr, const char * doc = nullptr, short attr = 0, bool ro = false, bool hidden = false) : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L447{addDynamicProperty}]]]
+adjustRelativeLinks(const std::set<App::DocumentObject *> & inList, std::set<App::DocumentObject *> * visited = nullptr) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L529{adjustRelativeLinks}]]]
+allowDuplicateLabel() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L411{allowDuplicateLabel}]]]
+canLinkProperties() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L408{canLinkProperties}]]]
+canLoadPartial() const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L538{canLoadPartial}]]]
+clearExpression(const App::ObjectIdentifier & path) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L433{clearExpression}]]]
+clearOutListCache() const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L235{clearOutListCache}]]]
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L98{create}]]]
+detachFromDocument() : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L146{detachFromDocument}]]]
+enforceRecompute() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L158{enforceRecompute}]]]
#execute() : App::DocumentObjectExecReturn * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L577{execute}]]]
#executeExtensions() : App::DocumentObjectExecReturn * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L582{executeExtensions}]]]
{static} +getClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L98{getClassTypeId}]]]
+getDocument() const : App::Document * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L148{getDocument}]]]
+getExportName(bool forced = false) const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L140{getExportName}]]]
+getExpression(const App::ObjectIdentifier & path) const : const PropertyExpressionEngine::ExpressionInfo [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L435{getExpression}]]]
+getFirstParent() const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L387{getFirstParent}]]]
+getFullLabel() const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L144{getFullLabel}]]]
+getFullName() const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L142{getFullName}]]]
+getGroup() const : App::DocumentObjectGroup * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L261{getGroup}]]]
+getID() const : long [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L138{getID}]]]
+getInList() const : const std::vector<App::DocumentObject *> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L242{getInList}]]]
+getInListEx(bool recursive) const : std::set<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L258{getInListEx}]]]
+getInListEx(std::set<App::DocumentObject *> & inSet, bool recursive, std::vector<App::DocumentObject *> * inList = nullptr) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L253{getInListEx}]]]
+getInListRecursive() const : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L245{getInListRecursive}]]]
+getLinkedObject(bool recurse = true, Base::Matrix4D * mat = nullptr, bool transform = false, int depth = 0) const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L404{getLinkedObject}]]]
+getNameInDocument() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L136{getNameInDocument}]]]
+getOldLabel() const : const std::string & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L439{getOldLabel}]]]
+getOutList() const : const std::vector<App::DocumentObject *> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L226{getOutList}]]]
+getOutList(int option) const : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L227{getOutList}]]]
+getOutList(int option, std::vector<App::DocumentObject *> & res) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L228{getOutList}]]]
+getOutListOfProperty(App::Property *) const : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L231{getOutListOfProperty}]]]
+getOutListRecursive() const : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L233{getOutListRecursive}]]]
+getParents(int depth = 0) const : std::vector<std::pair<App::DocumentObject *,std::string>> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L384{getParents}]]]
+getPathsByOutList(App::DocumentObject * to) const : std::vector<std::list<App::DocumentObject *>> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L237{getPathsByOutList}]]]
#getPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L98{getPropertyData}]]]
{static} #getPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L98{getPropertyDataPtr}]]]
+getPyObject() : PyObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L322{getPyObject}]]]
+getStatus() const : unsigned long [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L179{getStatus}]]]
+getStatusString() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L313{getStatusString}]]]
+getSubObject(const char * subname, PyObject ** pyObj = nullptr, Base::Matrix4D * mat = nullptr, bool transform = true, int depth = 0) const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L352{getSubObject}]]]
+getSubObjectList(const char * subname) const : std::vector<DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L356{getSubObjectList}]]]
+getSubObjects(int reason = 0) const : std::vector<std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L381{getSubObjects}]]]
+getTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L98{getTypeId}]]]
+getViewProviderName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L115{getViewProviderName}]]]
+getViewProviderNameOverride() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L127{getViewProviderNameOverride}]]]
+getViewProviderNameStored() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L441{getViewProviderNameStored}]]]
+hasChildElement() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L207{hasChildElement}]]]
{static} +hasHiddenMarker(const char * subname) : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L565{hasHiddenMarker}]]]
{static} +hiddenMarker() : const std::string & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L563{hiddenMarker}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L98{init}]]]
+isAttachedToDocument() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L145{isAttachedToDocument}]]]
+isElementVisible(const char * element) const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L204{isElementVisible}]]]
+isError() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L168{isError}]]]
+isExporting() const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L184{isExporting}]]]
+isInInList(App::DocumentObject * objToTest) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L266{isInInList}]]]
+isInInListRecursive(App::DocumentObject * objToTest) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L264{isInInListRecursive}]]]
+isInOutList(App::DocumentObject * objToTest) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L270{isInOutList}]]]
+isInOutListRecursive(App::DocumentObject * objToTest) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L268{isInOutListRecursive}]]]
+isRecomputing() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L173{isRecomputing}]]]
+isRemoving() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L177{isRemoving}]]]
+isRestoring() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L175{isRestoring}]]]
+isTouched() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L156{isTouched}]]]
+isValid() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L169{isValid}]]]
+mustExecute() const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L304{mustExecute}]]]
+mustRecompute() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L160{mustRecompute}]]]
#onBeforeChange(const App::Property * prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L605{onBeforeChange}]]]
+onBeforeChangeLabel(std::string & newLabel) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L419{onBeforeChangeLabel}]]]
#onChanged(const App::Property * prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L607{onChanged}]]]
#onDocumentRestored() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L609{onDocumentRestored}]]]
+onLostLinkToObject(App::DocumentObject *) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L321{onLostLinkToObject}]]]
#onPropertyStatusChanged(const App::Property & prop, unsigned long oldStatus) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L620{onPropertyStatusChanged}]]]
#onSettingDocument() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L613{onSettingDocument}]]]
#onUndoRedoFinished() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L611{onUndoRedoFinished}]]]
+onUpdateElementReference(const App::Property *) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L540{onUpdateElementReference}]]]
-printInvalidLinks() const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L623{printInvalidLinks}]]]
+purgeError() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L171{purgeError}]]]
+purgeTouched() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L162{purgeTouched}]]]
#recompute() : App::DocumentObjectExecReturn * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L569{recompute}]]]
+recomputeFeature(bool recursive = false) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L310{recomputeFeature}]]]
+redirectSubName(std::ostringstream & ss, App::DocumentObject * topParent, App::DocumentObject * child) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L555{redirectSubName}]]]
+removeDynamicProperty(const char * prop) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L445{removeDynamicProperty}]]]
+renameObjectIdentifiers(const std::map<App::ObjectIdentifier,App::ObjectIdentifier> & paths) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L437{renameObjectIdentifiers}]]]
#resetError() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L601{resetError}]]]
+resolve(const char * subname, App::DocumentObject ** parent = nullptr, std::string * childName = nullptr, const char ** subElement = nullptr, PyObject ** pyObj = nullptr, Base::Matrix4D * mat = nullptr, bool transform = true, int depth = 0) const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L464{resolve}]]]
+resolveRelativeLink(std::string & subname, App::DocumentObject *& link, std::string & linkSub) const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L512{resolveRelativeLink}]]]
#setDocument(App::Document * doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L602{setDocument}]]]
+setElementVisible(const char * element, bool visible) : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L197{setElementVisible}]]]
#setError() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L600{setError}]]]
+setExpression(const App::ObjectIdentifier & path, std::shared_ptr<App::Expression> expr) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L431{setExpression}]]]
+setStatus(App::ObjectStatus pos, bool on) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L181{setStatus}]]]
#setupObject() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L615{setupObject}]]]
+testIfLinkDAGCompatible(App::PropertyLinkSub & linkTo) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L290{testIfLinkDAGCompatible}]]]
+testIfLinkDAGCompatible(App::PropertyLinkSubList & linksTo) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L289{testIfLinkDAGCompatible}]]]
+testIfLinkDAGCompatible(const std::vector<DocumentObject *> & linksTo) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L288{testIfLinkDAGCompatible}]]]
+testIfLinkDAGCompatible(App::DocumentObject * linkTo) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L287{testIfLinkDAGCompatible}]]]
+testStatus(App::ObjectStatus pos) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L180{testStatus}]]]
+touch(bool noRecompute = false) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L154{touch}]]]
#unsetupObject() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L617{unsetupObject}]]]
__
+ExpressionEngine : App::PropertyExpressionEngine [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L104{ExpressionEngine}]]]
+Label : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L102{Label}]]]
+Label2 : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L103{Label2}]]]
#PythonObject : Py::SmartPtr [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L627{PythonObject}]]]
#StatusBits : std::bitset<32> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L598{StatusBits}]]]
{static} +StdReturn : App::DocumentObjectExecReturn * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L425{StdReturn}]]]
+Visibility : App::PropertyBool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L107{Visibility}]]]
-_Id : long [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L642{_Id}]]]
-_inList : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L647{_inList}]]]
-_outList : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L648{_outList}]]]
-_outListCached : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L650{_outListCached}]]]
-_outListMap : std::unordered_map<const char *,App::DocumentObject *,CStringHasher,CStringHasher> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L649{_outListMap}]]]
#_pDoc : App::Document * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L629{_pDoc}]]]
-_pcViewProviderName : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L639{_pcViewProviderName}]]]
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L98{classTypeId}]]]
#oldLabel : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L632{oldLabel}]]]
#pcNameInDocument : const std::string * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L635{pcNameInDocument}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L98{propertyData}]]]
+signalBeforeChange : boost::signals2::signal<void (const App::DocumentObject &,const App::Property &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L110{signalBeforeChange}]]]
+signalChanged : boost::signals2::signal<void (const App::DocumentObject &,const App::Property &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObject.h#L112{signalChanged}]]]
}
package [ExpressionParser] as C_0000905861183269213715 {
}
package [Meta] as C_0002283864520314866053 {
}
class "MaterialObject" as C_0000926193843063164156
class C_0000926193843063164156 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L34{MaterialObject}]] {
+MaterialObject() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L40{MaterialObject}]]]
+~MaterialObject() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L41{~MaterialObject}]]]
..
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L36{create}]]]
{static} +getClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L36{getClassTypeId}]]]
#getPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L36{getPropertyData}]]]
{static} #getPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L36{getPropertyDataPtr}]]]
+getTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L36{getTypeId}]]]
+getViewProviderName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L47{getViewProviderName}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L36{init}]]]
__
+Material : App::PropertyMap [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L43{Material}]]]
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L36{classTypeId}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.h#L36{propertyData}]]]
}
class "FeaturePythonT<App::MaterialObject>" as C_0000408176659655006496
class C_0000408176659655006496 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L55{FeaturePythonT}]] {
+FeaturePythonT() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L173{FeaturePythonT}]]]
+FeaturePythonT(const App::FeaturePythonT<App::MaterialObject> &) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L352{FeaturePythonT}]]]
+FeaturePythonT(App::FeaturePythonT<App::MaterialObject> &&) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L353{FeaturePythonT}]]]
+~FeaturePythonT() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L178{~FeaturePythonT}]]]
..
+operator=(const App::FeaturePythonT<App::MaterialObject> &) = deleted : App::FeaturePythonT<App::MaterialObject> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L354{operator=}]]]
+operator=(App::FeaturePythonT<App::MaterialObject> &&) = deleted : App::FeaturePythonT<App::MaterialObject> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L355{operator=}]]]
..
+allowDuplicateLabel() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L277{allowDuplicateLabel}]]]
+canLinkProperties() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L266{canLinkProperties}]]]
+canLoadPartial() const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L301{canLoadPartial}]]]
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L48{create}]]]
+editProperty(const char * propName) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L308{editProperty}]]]
+execute() : App::DocumentObjectExecReturn * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L192{execute}]]]
{static} +getClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L48{getClassTypeId}]]]
+getLinkedObject(bool recurse, Base::Matrix4D * mat, bool transform, int depth) const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L231{getLinkedObject}]]]
#getPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L48{getPropertyData}]]]
{static} #getPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L48{getPropertyDataPtr}]]]
+getPyObject() : PyObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L313{getPyObject}]]]
+getSubObject(const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L215{getSubObject}]]]
+getSubObjects(int reason) const : std::vector<std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L224{getSubObjects}]]]
+getTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L48{getTypeId}]]]
+getViewProviderName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L49{getViewProviderName}]]]
+getViewProviderNameOverride() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L203{getViewProviderNameOverride}]]]
+hasChildElement() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L241{hasChildElement}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L48{init}]]]
+isElementVisible(const char * element) const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L252{isElementVisible}]]]
+mustExecute() const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L184{mustExecute}]]]
#onBeforeChange(const App::Property * prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L328{onBeforeChange}]]]
#onBeforeChangeLabel(std::string & newLabel) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L332{onBeforeChangeLabel}]]]
#onChanged(const App::Property * prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L336{onChanged}]]]
#onDocumentRestored() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L342{onDocumentRestored}]]]
+redirectSubName(std::ostringstream & ss, App::DocumentObject * topParent, App::DocumentObject * child) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L288{redirectSubName}]]]
+setElementVisible(const char * element, bool visible) : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L259{setElementVisible}]]]
+setPyObject(PyObject * obj) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L320{setPyObject}]]]
#unsetupObject() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L346{unsetupObject}]]]
__
-Proxy : App::PropertyPythonObject [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L359{Proxy}]]]
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L48{classTypeId}]]]
-imp : App::FeaturePythonImp * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L358{imp}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/MaterialObject.cpp#L48{propertyData}]]]
-viewProviderName : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/FeaturePython.h#L360{viewProviderName}]]]
}
}
C_0001065140174462797402 --> C_0001065140174462797402 : +parentPropertyData
C_0002237031220373524384 --> C_0001299587473968259399 : -classTypeId
C_0001679842198945066576 --> C_0001299587473968259399 : -classTypeId
C_0001679842198945066576 --> C_0001065140174462797402 : -propertyData
C_0000926193843063164156 o-- C_0002237031220373524384 : +Material
C_0000926193843063164156 --> C_0001299587473968259399 : -classTypeId
C_0000926193843063164156 --> C_0001065140174462797402 : -propertyData
C_0001679842198945066576 <|-- C_0000926193843063164156
C_0000408176659655006496 --> C_0001299587473968259399 : -classTypeId
C_0000408176659655006496 --> C_0001065140174462797402 : -propertyData
C_0000926193843063164156 <|-- C_0000408176659655006496

'Generated with clang-uml, version 0.4.0-14-g26abb71
'LLVM version Ubuntu clang version 15.0.7
@enduml
