@startuml
title App::DocumentObserverPython context
package [App] as C_0002285326295477687690 {
class "DocumentObserverPython" as C_0001615342421965561109
class C_0001615342421965561109 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L38{DocumentObserverPython}]] {
+DocumentObserverPython(const Py::Object & obj) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L43{DocumentObserverPython}]]]
+~DocumentObserverPython() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L44{~DocumentObserverPython}]]]
..
{static} +addObserver(const Py::Object & obj) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L46{addObserver}]]]
{static} +removeObserver(const Py::Object & obj) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L47{removeObserver}]]]
-slotAbortTransaction(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L85{slotAbortTransaction}]]]
-slotActivateDocument(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L57{slotActivateDocument}]]]
-slotAddedDynamicExtension(const App::ExtensionContainer &, std::string extension) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L107{slotAddedDynamicExtension}]]]
-slotAppendDynamicProperty(const App::Property & Prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L95{slotAppendDynamicProperty}]]]
-slotBeforeAddingDynamicExtension(const App::ExtensionContainer &, std::string extension) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L105{slotBeforeAddingDynamicExtension}]]]
-slotBeforeChangeDocument(const App::Document & Obj, const App::Property & Prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L59{slotBeforeChangeDocument}]]]
-slotBeforeChangeObject(const App::DocumentObject & Obj, const App::Property & Prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L67{slotBeforeChangeObject}]]]
-slotBeforeCloseTransaction(bool abort) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L91{slotBeforeCloseTransaction}]]]
-slotBeforeRecomputeDocument(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L77{slotBeforeRecomputeDocument}]]]
-slotChangePropertyEditor(const App::Document & Doc, const App::Property & Prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L99{slotChangePropertyEditor}]]]
-slotChangedDocument(const App::Document & Obj, const App::Property & Prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L61{slotChangedDocument}]]]
-slotChangedObject(const App::DocumentObject & Obj, const App::Property & Prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L69{slotChangedObject}]]]
-slotCloseTransaction(bool abort) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L93{slotCloseTransaction}]]]
-slotCommitTransaction(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L83{slotCommitTransaction}]]]
-slotCreatedDocument(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L51{slotCreatedDocument}]]]
-slotCreatedObject(const App::DocumentObject & Obj) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L63{slotCreatedObject}]]]
-slotDeletedDocument(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L53{slotDeletedDocument}]]]
-slotDeletedObject(const App::DocumentObject & Obj) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L65{slotDeletedObject}]]]
-slotFinishSaveDocument(const App::Document &, const std::string &) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L103{slotFinishSaveDocument}]]]
-slotOpenTransaction(const App::Document & Doc, std::string str) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L81{slotOpenTransaction}]]]
-slotRecomputedDocument(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L79{slotRecomputedDocument}]]]
-slotRecomputedObject(const App::DocumentObject & Obj) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L75{slotRecomputedObject}]]]
-slotRedo() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L89{slotRedo}]]]
-slotRedoDocument(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L73{slotRedoDocument}]]]
-slotRelabelDocument(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L55{slotRelabelDocument}]]]
-slotRemoveDynamicProperty(const App::Property & Prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L97{slotRemoveDynamicProperty}]]]
-slotStartSaveDocument(const App::Document &, const std::string &) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L101{slotStartSaveDocument}]]]
-slotUndo() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L87{slotUndo}]]]
-slotUndoDocument(const App::Document & Doc) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L71{slotUndoDocument}]]]
__
{static} -_instances : std::vector<DocumentObserverPython *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L112{_instances}]]]
-inst : Py::Object [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L111{inst}]]]
-pyAbortTransaction : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L139{pyAbortTransaction}]]]
-pyActivateDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L125{pyActivateDocument}]]]
-pyAddedDynamicExtension : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L150{pyAddedDynamicExtension}]]]
-pyAppendDynamicProperty : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L146{pyAppendDynamicProperty}]]]
-pyBeforeAddingDynamicExtension : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L149{pyBeforeAddingDynamicExtension}]]]
-pyBeforeChangeDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L128{pyBeforeChangeDocument}]]]
-pyBeforeChangeObject : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L132{pyBeforeChangeObject}]]]
-pyBeforeCloseTransaction : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L142{pyBeforeCloseTransaction}]]]
-pyBeforeRecomputeDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L135{pyBeforeRecomputeDocument}]]]
-pyChangePropertyEditor : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L148{pyChangePropertyEditor}]]]
-pyChangedDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L129{pyChangedDocument}]]]
-pyChangedObject : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L133{pyChangedObject}]]]
-pyCloseTransaction : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L143{pyCloseTransaction}]]]
-pyCommitTransaction : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L138{pyCommitTransaction}]]]
-pyCreatedDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L122{pyCreatedDocument}]]]
-pyCreatedObject : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L130{pyCreatedObject}]]]
-pyDeletedDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L123{pyDeletedDocument}]]]
-pyDeletedObject : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L131{pyDeletedObject}]]]
-pyFinishSaveDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L145{pyFinishSaveDocument}]]]
-pyOpenTransaction : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L137{pyOpenTransaction}]]]
-pyRecomputedDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L136{pyRecomputedDocument}]]]
-pyRecomputedObject : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L134{pyRecomputedObject}]]]
-pyRedo : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L141{pyRedo}]]]
-pyRedoDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L127{pyRedoDocument}]]]
-pyRelabelDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L124{pyRelabelDocument}]]]
-pyRemoveDynamicProperty : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L147{pyRemoveDynamicProperty}]]]
-pyStartSaveDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L144{pyStartSaveDocument}]]]
-pyUndo : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L140{pyUndo}]]]
-pyUndoDocument : App::DocumentObserverPython::Connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L126{pyUndoDocument}]]]
}
class "DocumentObserverPython::PythonObject" as C_0000364767694530174942
class C_0000364767694530174942 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L114{DocumentObserverPython##PythonObject}]] {
+ptr() : PyObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L117{ptr}]]]
__
+py : Py::Object [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L116{py}]]]
+slot : boost::signals2::scoped_connection [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DocumentObserverPython.h#L115{slot}]]]
}
package [ExpressionParser] as C_0000905861183269213715 {
}
package [Meta] as C_0002283864520314866053 {
}
}
package [Py] as C_0000849183934795741319 {
class "Object" as C_0000439997732801671885
class C_0000439997732801671885 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L142{Object}]] {
+Object(PyObject * pyob = Py::_None(), bool owned = false) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L174{Object}]]]
+Object(const Py::Object & ob) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L185{Object}]]]
+~Object() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L208{~Object}]]]
..
+operator=(const Py::Object & rhs) : Py::Object & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L193{operator=}]]]
..
+operator*() const : PyObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L214{operator*}]]]
+operator=(PyObject * rhsp) : Py::Object & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L199{operator=}]]]
..
+accepts(PyObject *) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L246{accepts}]]]
+as_bool() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L292{as_bool}]]]
+as_string() const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L261{as_string}]]]
+callMemberFunction(const std::string & function_name, const Py::Tuple & args, const Py::Dict & kw) const : Py::Object [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L279{callMemberFunction}]]]
+callMemberFunction(const std::string & function_name, const Py::Tuple & args) const : Py::Object [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L278{callMemberFunction}]]]
+callMemberFunction(const std::string & function_name) const : Py::Object [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L277{callMemberFunction}]]]
+decrement_reference_count() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L225{decrement_reference_count}]]]
+delAttr(const std::string & s) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L383{delAttr}]]]
+delItem(const Py::Object & key) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L394{delItem}]]]
+dir() const : Py::List [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L265{dir}]]]
+getAttr(const std::string & s) const : Py::Object [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L272{getAttr}]]]
+getItem(const Py::Object & key) const : Py::Object [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L281{getItem}]]]
+hasAttr(const std::string & s) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L267{hasAttr}]]]
+hashValue() const : Py_hash_t [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L286{hashValue}]]]
+increment_reference_count() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L220{increment_reference_count}]]]
+is(const Py::Object & other) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L302{is}]]]
+is(PyObject * pother) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L297{is}]]]
+isBoolean() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L369{isBoolean}]]]
+isBytes() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L364{isBytes}]]]
+isCallable() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L317{isCallable}]]]
+isDict() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L322{isDict}]]]
+isList() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L327{isList}]]]
+isMapping() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L332{isMapping}]]]
+isNone() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L312{isNone}]]]
+isNull() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L307{isNull}]]]
+isNumeric() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L337{isNumeric}]]]
+isSequence() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L342{isSequence}]]]
+isString() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L359{isString}]]]
+isTrue() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L347{isTrue}]]]
+isTuple() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L354{isTuple}]]]
+isType(const Py::Type & t) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L352{isType}]]]
+ptr() const : PyObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L236{ptr}]]]
+reference_count() const : Py_ssize_t [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L252{reference_count}]]]
#release() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L164{release}]]]
+repr() const : Py::String [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L263{repr}]]]
#set(PyObject * pyob, bool owned = false) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L153{set}]]]
+setAttr(const std::string & s, const Py::Object & value) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L375{setAttr}]]]
+str() const : Py::String [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L259{str}]]]
+type() const : Py::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L257{type}]]]
#validate() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L170{validate}]]]
__
-p : PyObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/CXX/Python3/Objects.hxx#L150{p}]]]
}
}
C_0001615342421965561109 o-- C_0000439997732801671885 : -inst
C_0001615342421965561109 --> C_0001615342421965561109 : -_instances
C_0000364767694530174942 --+ C_0001615342421965561109
C_0000364767694530174942 o-- C_0000439997732801671885 : +py

'Generated with clang-uml, version 0.4.0-14-g26abb71
'LLVM version Ubuntu clang version 15.0.7
@enduml
