@startuml
title App::ExtensionPython context
package [Base] as C_0000701777446892506059 {
class "Type" as C_0001299587473968259399
class C_0001299587473968259399 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L80{Type}]] {
+Type(const Base::Type & type) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L84{Type}]]]
+Type() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L85{Type}]]]
+~Type() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L87{~Type}]]]
..
+operator=(const Base::Type type) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L114{operator=}]]]
..
+operator!=(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L116{operator!=}]]]
+operator<(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L118{operator<}]]]
+operator<=(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L119{operator<=}]]]
+operator==(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L115{operator==}]]]
+operator>(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L121{operator>}]]]
+operator>=(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L120{operator>=}]]]
..
{static} +badType() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L123{badType}]]]
+createInstance() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L90{createInstance}]]]
{static} +createInstanceByName(const char * TypeName, bool bLoadModule = false) : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L92{createInstanceByName}]]]
{static} +createType(const Base::Type parent, const char * name, Base::Type::instantiationMethod method = nullptr) : const Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L109{createType}]]]
{static} +destruct() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L125{destruct}]]]
{static} +fromKey(unsigned int key) : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L98{fromKey}]]]
{static} +fromName(const char * name) : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L97{fromName}]]]
{static} +getAllDerivedFrom(const Base::Type type, std::vector<Type> & List) : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L103{getAllDerivedFrom}]]]
+getKey() const : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L111{getKey}]]]
{static} #getModuleName(const char * ClassName) : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L128{getModuleName}]]]
+getName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L99{getName}]]]
{static} +getNumTypes() : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L107{getNumTypes}]]]
+getParent() const : const Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L100{getParent}]]]
{static} +getTypeIfDerivedFrom(const char * name, const Base::Type parent, bool bLoadModule = false) : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L105{getTypeIfDerivedFrom}]]]
{static} +importModule(const char * TypeName) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L93{importModule}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L124{init}]]]
+isBad() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L112{isBad}]]]
+isDerivedFrom(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L101{isDerivedFrom}]]]
__
-index : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L134{index}]]]
{static} -loadModuleSet : std::set<std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L140{loadModuleSet}]]]
{static} -typedata : std::vector<TypeData *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L138{typedata}]]]
{static} -typemap : std::map<std::string,unsigned int> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L137{typemap}]]]
}
}
package [App] as C_0002285326295477687690 {
class "PropertyData" as C_0001065140174462797402
class C_0001065140174462797402 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L56{PropertyData}]] {
+addProperty(App::PropertyData::OffsetBase offsetBase, const char * PropName, App::Property * Prop, const char * PropertyGroup = nullptr, App::PropertyType  = Prop_None, const char * PropertyDocu = nullptr) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L116{addProperty}]]]
+findProperty(App::PropertyData::OffsetBase offsetBase, const char * PropName) const : const App::PropertyData::PropertySpec * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L118{findProperty}]]]
+findProperty(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const App::PropertyData::PropertySpec * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L119{findProperty}]]]
+getDocumentation(App::PropertyData::OffsetBase offsetBase, const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L126{getDocumentation}]]]
+getDocumentation(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L127{getDocumentation}]]]
+getGroup(App::PropertyData::OffsetBase offsetBase, const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L124{getGroup}]]]
+getGroup(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L125{getGroup}]]]
+getName(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L121{getName}]]]
+getPropertyByName(App::PropertyData::OffsetBase offsetBase, const char * name) const : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L129{getPropertyByName}]]]
+getPropertyList(App::PropertyData::OffsetBase offsetBase, std::vector<Property *> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L131{getPropertyList}]]]
+getPropertyMap(App::PropertyData::OffsetBase offsetBase, std::map<std::string,Property *> & Map) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L130{getPropertyMap}]]]
+getPropertyNamedList(App::PropertyData::OffsetBase offsetBase, std::vector<std::pair<const char *,Property *>> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L132{getPropertyNamedList}]]]
+getType(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L122{getType}]]]
+getType(App::PropertyData::OffsetBase offsetBase, const char * name) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L123{getType}]]]
+merge(App::PropertyData * other = nullptr) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L134{merge}]]]
+split(App::PropertyData * other) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L135{split}]]]
__
+parentMerged : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L112{parentMerged}]]]
+parentPropertyData : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L114{parentPropertyData}]]]
+propertyData : bmi::multi_index_container<PropertySpec,bmi::indexed_by<bmi::sequenced<>,bmi::hashed_unique<bmi::member<PropertySpec,const char *,&PropertySpec::Name>,CStringHasher,CStringHasher>,bmi::hashed_unique<bmi::member<PropertySpec,short,&PropertySpec::Offset>>>> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L110{propertyData}]]]
}
class "ExtensionPythonT<ExtensionT>" as C_0001052415304501626199
class C_0001052415304501626199 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L38{ExtensionPythonT}]] {
+ExtensionPythonT() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L45{ExtensionPythonT}]]]
+ExtensionPythonT(const ExtensionPythonT<ExtensionT> &) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L51{ExtensionPythonT}]]]
+ExtensionPythonT(ExtensionPythonT<ExtensionT> &&) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L52{ExtensionPythonT}]]]
+~ExtensionPythonT() = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L49{~ExtensionPythonT}]]]
..
+operator=(const ExtensionPythonT<ExtensionT> &) = deleted : ExtensionPythonT<ExtensionT> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L53{operator=}]]]
+operator=(ExtensionPythonT<ExtensionT> &&) = deleted : ExtensionPythonT<ExtensionT> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L54{operator=}]]]
..
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L40{create}]]]
#extensionGetPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L40{extensionGetPropertyData}]]]
{static} #extensionGetPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L40{extensionGetPropertyDataPtr}]]]
{static} +getExtensionClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L40{getExtensionClassTypeId}]]]
+getExtensionTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L40{getExtensionTypeId}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L40{init}]]]
__
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L40{classTypeId}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L40{propertyData}]]]
}
class "ExtensionPythonT<App::GroupExtensionPythonT<App::GroupExtension>>" as C_0001830979336005663904
class C_0001830979336005663904 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GroupExtension.cpp#L42{ExtensionPythonT}]] {
+ExtensionPythonT() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L45{ExtensionPythonT}]]]
+ExtensionPythonT(const App::ExtensionPythonT<GroupExtensionPythonT<App::GroupExtension>> &) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L51{ExtensionPythonT}]]]
+ExtensionPythonT(App::ExtensionPythonT<GroupExtensionPythonT<App::GroupExtension>> &&) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L52{ExtensionPythonT}]]]
+~ExtensionPythonT() = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L49{~ExtensionPythonT}]]]
..
+operator=(const App::ExtensionPythonT<GroupExtensionPythonT<App::GroupExtension>> &) = deleted : App::ExtensionPythonT<GroupExtensionPythonT<App::GroupExtension>> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L53{operator=}]]]
+operator=(App::ExtensionPythonT<GroupExtensionPythonT<App::GroupExtension>> &&) = deleted : App::ExtensionPythonT<GroupExtensionPythonT<App::GroupExtension>> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L54{operator=}]]]
..
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GroupExtension.cpp#L39{create}]]]
#extensionGetPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GroupExtension.cpp#L39{extensionGetPropertyData}]]]
{static} #extensionGetPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GroupExtension.cpp#L39{extensionGetPropertyDataPtr}]]]
{static} +getExtensionClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GroupExtension.cpp#L39{getExtensionClassTypeId}]]]
+getExtensionTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GroupExtension.cpp#L39{getExtensionTypeId}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GroupExtension.cpp#L39{init}]]]
__
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GroupExtension.cpp#L39{classTypeId}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GroupExtension.cpp#L39{propertyData}]]]
}
class "ExtensionPythonT<App::Extension>" as C_0001976434673191902003
class C_0001976434673191902003 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Extension.cpp#L212{ExtensionPythonT}]] {
+ExtensionPythonT() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L45{ExtensionPythonT}]]]
+ExtensionPythonT(const App::ExtensionPythonT<App::Extension> &) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L51{ExtensionPythonT}]]]
+ExtensionPythonT(App::ExtensionPythonT<App::Extension> &&) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L52{ExtensionPythonT}]]]
+~ExtensionPythonT() = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L49{~ExtensionPythonT}]]]
..
+operator=(const App::ExtensionPythonT<App::Extension> &) = deleted : App::ExtensionPythonT<App::Extension> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L53{operator=}]]]
+operator=(App::ExtensionPythonT<App::Extension> &&) = deleted : App::ExtensionPythonT<App::Extension> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L54{operator=}]]]
..
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Extension.cpp#L209{create}]]]
#extensionGetPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Extension.cpp#L209{extensionGetPropertyData}]]]
{static} #extensionGetPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Extension.cpp#L209{extensionGetPropertyDataPtr}]]]
{static} +getExtensionClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Extension.cpp#L209{getExtensionClassTypeId}]]]
+getExtensionTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Extension.cpp#L209{getExtensionTypeId}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Extension.cpp#L209{init}]]]
__
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Extension.cpp#L209{classTypeId}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Extension.cpp#L209{propertyData}]]]
}
package [ExpressionParser] as C_0000905861183269213715 {
}
package [Meta] as C_0002283864520314866053 {
}
class "ExtensionPythonT<App::GroupExtensionPythonT<App::GeoFeatureGroupExtension>>" as C_0000854941210377690479
class C_0000854941210377690479 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GeoFeatureGroupExtension.cpp#L505{ExtensionPythonT}]] {
+ExtensionPythonT() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L45{ExtensionPythonT}]]]
+ExtensionPythonT(const App::ExtensionPythonT<GroupExtensionPythonT<App::GeoFeatureGroupExtension>> &) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L51{ExtensionPythonT}]]]
+ExtensionPythonT(App::ExtensionPythonT<GroupExtensionPythonT<App::GeoFeatureGroupExtension>> &&) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L52{ExtensionPythonT}]]]
+~ExtensionPythonT() = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L49{~ExtensionPythonT}]]]
..
+operator=(const App::ExtensionPythonT<GroupExtensionPythonT<App::GeoFeatureGroupExtension>> &) = deleted : App::ExtensionPythonT<GroupExtensionPythonT<App::GeoFeatureGroupExtension>> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L53{operator=}]]]
+operator=(App::ExtensionPythonT<GroupExtensionPythonT<App::GeoFeatureGroupExtension>> &&) = deleted : App::ExtensionPythonT<GroupExtensionPythonT<App::GeoFeatureGroupExtension>> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L54{operator=}]]]
..
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GeoFeatureGroupExtension.cpp#L502{create}]]]
#extensionGetPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GeoFeatureGroupExtension.cpp#L502{extensionGetPropertyData}]]]
{static} #extensionGetPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GeoFeatureGroupExtension.cpp#L502{extensionGetPropertyDataPtr}]]]
{static} +getExtensionClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GeoFeatureGroupExtension.cpp#L502{getExtensionClassTypeId}]]]
+getExtensionTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GeoFeatureGroupExtension.cpp#L502{getExtensionTypeId}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GeoFeatureGroupExtension.cpp#L502{init}]]]
__
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GeoFeatureGroupExtension.cpp#L502{classTypeId}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/GeoFeatureGroupExtension.cpp#L502{propertyData}]]]
}
class "ExtensionPythonT<App::LinkBaseExtension>" as C_0000944664542276527152
class C_0000944664542276527152 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2219{ExtensionPythonT}]] {
+ExtensionPythonT() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L45{ExtensionPythonT}]]]
+ExtensionPythonT(const App::ExtensionPythonT<App::LinkBaseExtension> &) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L51{ExtensionPythonT}]]]
+ExtensionPythonT(App::ExtensionPythonT<App::LinkBaseExtension> &&) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L52{ExtensionPythonT}]]]
+~ExtensionPythonT() = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L49{~ExtensionPythonT}]]]
..
+operator=(const App::ExtensionPythonT<App::LinkBaseExtension> &) = deleted : App::ExtensionPythonT<App::LinkBaseExtension> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L53{operator=}]]]
+operator=(App::ExtensionPythonT<App::LinkBaseExtension> &&) = deleted : App::ExtensionPythonT<App::LinkBaseExtension> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L54{operator=}]]]
..
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2216{create}]]]
#extensionGetPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2216{extensionGetPropertyData}]]]
{static} #extensionGetPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2216{extensionGetPropertyDataPtr}]]]
{static} +getExtensionClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2216{getExtensionClassTypeId}]]]
+getExtensionTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2216{getExtensionTypeId}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2216{init}]]]
__
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2216{classTypeId}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2216{propertyData}]]]
}
class "ExtensionPythonT<App::LinkExtension>" as C_0001898311921165259382
class C_0001898311921165259382 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2244{ExtensionPythonT}]] {
+ExtensionPythonT() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L45{ExtensionPythonT}]]]
+ExtensionPythonT(const App::ExtensionPythonT<App::LinkExtension> &) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L51{ExtensionPythonT}]]]
+ExtensionPythonT(App::ExtensionPythonT<App::LinkExtension> &&) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L52{ExtensionPythonT}]]]
+~ExtensionPythonT() = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L49{~ExtensionPythonT}]]]
..
+operator=(const App::ExtensionPythonT<App::LinkExtension> &) = deleted : App::ExtensionPythonT<App::LinkExtension> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L53{operator=}]]]
+operator=(App::ExtensionPythonT<App::LinkExtension> &&) = deleted : App::ExtensionPythonT<App::LinkExtension> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L54{operator=}]]]
..
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2241{create}]]]
#extensionGetPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2241{extensionGetPropertyData}]]]
{static} #extensionGetPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2241{extensionGetPropertyDataPtr}]]]
{static} +getExtensionClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2241{getExtensionClassTypeId}]]]
+getExtensionTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2241{getExtensionTypeId}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2241{init}]]]
__
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2241{classTypeId}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Link.cpp#L2241{propertyData}]]]
}
class "ExtensionPythonT<App::GroupExtensionPythonT<App::OriginGroupExtension>>" as C_0000375757368784478187
class C_0000375757368784478187 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/OriginGroupExtension.cpp#L264{ExtensionPythonT}]] {
+ExtensionPythonT() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L45{ExtensionPythonT}]]]
+ExtensionPythonT(const App::ExtensionPythonT<GroupExtensionPythonT<App::OriginGroupExtension>> &) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L51{ExtensionPythonT}]]]
+ExtensionPythonT(App::ExtensionPythonT<GroupExtensionPythonT<App::OriginGroupExtension>> &&) = deleted : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L52{ExtensionPythonT}]]]
+~ExtensionPythonT() = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L49{~ExtensionPythonT}]]]
..
+operator=(const App::ExtensionPythonT<GroupExtensionPythonT<App::OriginGroupExtension>> &) = deleted : App::ExtensionPythonT<GroupExtensionPythonT<App::OriginGroupExtension>> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L53{operator=}]]]
+operator=(App::ExtensionPythonT<GroupExtensionPythonT<App::OriginGroupExtension>> &&) = deleted : App::ExtensionPythonT<GroupExtensionPythonT<App::OriginGroupExtension>> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionPython.h#L54{operator=}]]]
..
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/OriginGroupExtension.cpp#L261{create}]]]
#extensionGetPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/OriginGroupExtension.cpp#L261{extensionGetPropertyData}]]]
{static} #extensionGetPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/OriginGroupExtension.cpp#L261{extensionGetPropertyDataPtr}]]]
{static} +getExtensionClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/OriginGroupExtension.cpp#L261{getExtensionClassTypeId}]]]
+getExtensionTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/OriginGroupExtension.cpp#L261{getExtensionTypeId}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/OriginGroupExtension.cpp#L261{init}]]]
__
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/OriginGroupExtension.cpp#L261{classTypeId}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/OriginGroupExtension.cpp#L261{propertyData}]]]
}
}
C_0001065140174462797402 --> C_0001065140174462797402 : +parentPropertyData
C_0001052415304501626199 --> C_0001299587473968259399 : -classTypeId
C_0001052415304501626199 --> C_0001065140174462797402 : -propertyData
C_0001830979336005663904 ..|> C_0001052415304501626199
C_0001830979336005663904 --> C_0001299587473968259399 : -classTypeId
C_0001830979336005663904 --> C_0001065140174462797402 : -propertyData
C_0001976434673191902003 ..|> C_0001052415304501626199
C_0001976434673191902003 --> C_0001299587473968259399 : -classTypeId
C_0001976434673191902003 --> C_0001065140174462797402 : -propertyData
C_0000854941210377690479 ..|> C_0001052415304501626199
C_0000854941210377690479 --> C_0001299587473968259399 : -classTypeId
C_0000854941210377690479 --> C_0001065140174462797402 : -propertyData
C_0000944664542276527152 ..|> C_0001052415304501626199
C_0000944664542276527152 --> C_0001299587473968259399 : -classTypeId
C_0000944664542276527152 --> C_0001065140174462797402 : -propertyData
C_0001898311921165259382 ..|> C_0001052415304501626199
C_0001898311921165259382 --> C_0001299587473968259399 : -classTypeId
C_0001898311921165259382 --> C_0001065140174462797402 : -propertyData
C_0000375757368784478187 ..|> C_0001052415304501626199
C_0000375757368784478187 --> C_0001299587473968259399 : -classTypeId
C_0000375757368784478187 --> C_0001065140174462797402 : -propertyData

'Generated with clang-uml, version 0.4.0-14-g26abb71
'LLVM version Ubuntu clang version 15.0.7
@enduml
