@startuml
title App::PropertyContainer context
package [Base] as C_0000701777446892506059 {
class "Type" as C_0001299587473968259399
class C_0001299587473968259399 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L80{Type}]] {
+Type(const Base::Type & type) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L84{Type}]]]
+Type() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L85{Type}]]]
+~Type() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L87{~Type}]]]
..
+operator=(const Base::Type type) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L114{operator=}]]]
..
+operator!=(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L116{operator!=}]]]
+operator<(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L118{operator<}]]]
+operator<=(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L119{operator<=}]]]
+operator==(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L115{operator==}]]]
+operator>(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L121{operator>}]]]
+operator>=(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L120{operator>=}]]]
..
{static} +badType() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L123{badType}]]]
+createInstance() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L90{createInstance}]]]
{static} +createInstanceByName(const char * TypeName, bool bLoadModule = false) : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L92{createInstanceByName}]]]
{static} +createType(const Base::Type parent, const char * name, Base::Type::instantiationMethod method = nullptr) : const Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L109{createType}]]]
{static} +destruct() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L125{destruct}]]]
{static} +fromKey(unsigned int key) : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L98{fromKey}]]]
{static} +fromName(const char * name) : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L97{fromName}]]]
{static} +getAllDerivedFrom(const Base::Type type, std::vector<Type> & List) : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L103{getAllDerivedFrom}]]]
+getKey() const : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L111{getKey}]]]
{static} #getModuleName(const char * ClassName) : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L128{getModuleName}]]]
+getName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L99{getName}]]]
{static} +getNumTypes() : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L107{getNumTypes}]]]
+getParent() const : const Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L100{getParent}]]]
{static} +getTypeIfDerivedFrom(const char * name, const Base::Type parent, bool bLoadModule = false) : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L105{getTypeIfDerivedFrom}]]]
{static} +importModule(const char * TypeName) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L93{importModule}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L124{init}]]]
+isBad() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L112{isBad}]]]
+isDerivedFrom(const Base::Type type) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L101{isDerivedFrom}]]]
__
-index : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L134{index}]]]
{static} -loadModuleSet : std::set<std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L140{loadModuleSet}]]]
{static} -typedata : std::vector<TypeData *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L138{typedata}]]]
{static} -typemap : std::map<std::string,unsigned int> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Type.h#L137{typemap}]]]
}
abstract "Persistence" as C_0001441097518118859586
abstract C_0001441097518118859586 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L36{Persistence}]] {
{abstract} +Restore(Base::XMLReader &) = 0 : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L79{Restore}]]]
+RestoreDocFile(Base::Reader &) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L143{RestoreDocFile}]]]
{abstract} +Save(Base::Writer &) const = 0 : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L63{Save}]]]
+SaveDocFile(Base::Writer &) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L113{SaveDocFile}]]]
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L39{create}]]]
+dumpToStream(std::ostream & stream, int compression) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L148{dumpToStream}]]]
{static} +encodeAttribute(const std::string &) : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L145{encodeAttribute}]]]
{static} +getClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L39{getClassTypeId}]]]
{abstract} +getMemSize() const = 0 : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L46{getMemSize}]]]
+getTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L39{getTypeId}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L39{init}]]]
-restoreFinished() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L159{restoreFinished}]]]
+restoreFromStream(std::istream & stream) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L151{restoreFromStream}]]]
__
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/Base/Persistence.h#L39{classTypeId}]]]
}
}
package [App] as C_0002285326295477687690 {
class "DynamicProperty" as C_0000874376245777698770
class C_0000874376245777698770 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L67{DynamicProperty}]] {
+DynamicProperty() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L70{DynamicProperty}]]]
+~DynamicProperty() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L71{~DynamicProperty}]]]
..
+addDynamicProperty(App::PropertyContainer & pc, const char * type, const char * name = nullptr, const char * group = nullptr, const char * doc = nullptr, short attr = 0, bool ro = false, bool hidden = false) : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L100{addDynamicProperty}]]]
+addProperty(App::Property * prop) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L108{addProperty}]]]
+changeDynamicProperty(const App::Property * prop, const char * group, const char * doc) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L172{changeDynamicProperty}]]]
+clear() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L139{clear}]]]
+getDynamicPropertyByName(const char * name) const : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L82{getDynamicPropertyByName}]]]
+getDynamicPropertyData(const App::Property * prop) const : App::DynamicProperty::PropData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L170{getDynamicPropertyData}]]]
+getDynamicPropertyNames() const : std::vector<std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L117{getDynamicPropertyNames}]]]
+getPropertyDocumentation(const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L133{getPropertyDocumentation}]]]
+getPropertyDocumentation(const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L135{getPropertyDocumentation}]]]
+getPropertyGroup(const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L129{getPropertyGroup}]]]
+getPropertyGroup(const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L131{getPropertyGroup}]]]
+getPropertyList(std::vector<Property *> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L76{getPropertyList}]]]
+getPropertyMap(std::map<std::string,Property *> & Map) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L80{getPropertyMap}]]]
+getPropertyName(const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L119{getPropertyName}]]]
+getPropertyNamedList(std::vector<std::pair<const char *,Property *>> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L78{getPropertyNamedList}]]]
+getPropertyType(const char * name) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L127{getPropertyType}]]]
+getPropertyType(const App::Property * prop) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L125{getPropertyType}]]]
-getUniquePropertyName(App::PropertyContainer & pc, const char * Name) const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L175{getUniquePropertyName}]]]
+removeDynamicProperty(const char * name) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L113{removeDynamicProperty}]]]
+removeProperty(const App::Property * prop) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L115{removeProperty}]]]
+restore(App::PropertyContainer & pc, const char * PropName, const char * TypeName, Base::XMLReader & reader) : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L146{restore}]]]
+save(const App::Property * prop, Base::Writer & writer) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L144{save}]]]
+size() const : size_t [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L142{size}]]]
__
-props : bmi::multi_index_container<PropData,bmi::indexed_by<bmi::hashed_unique<bmi::const_mem_fun<PropData,const char *,&PropData::getName>,CStringHasher,CStringHasher>,bmi::hashed_unique<bmi::member<PropData,Property *,&PropData::property>>>> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/DynamicProperty.h#L190{props}]]]
}
class "PropertyData" as C_0001065140174462797402
class C_0001065140174462797402 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L56{PropertyData}]] {
+addProperty(App::PropertyData::OffsetBase offsetBase, const char * PropName, App::Property * Prop, const char * PropertyGroup = nullptr, App::PropertyType  = Prop_None, const char * PropertyDocu = nullptr) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L116{addProperty}]]]
+findProperty(App::PropertyData::OffsetBase offsetBase, const char * PropName) const : const App::PropertyData::PropertySpec * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L118{findProperty}]]]
+findProperty(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const App::PropertyData::PropertySpec * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L119{findProperty}]]]
+getDocumentation(App::PropertyData::OffsetBase offsetBase, const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L126{getDocumentation}]]]
+getDocumentation(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L127{getDocumentation}]]]
+getGroup(App::PropertyData::OffsetBase offsetBase, const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L124{getGroup}]]]
+getGroup(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L125{getGroup}]]]
+getName(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L121{getName}]]]
+getPropertyByName(App::PropertyData::OffsetBase offsetBase, const char * name) const : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L129{getPropertyByName}]]]
+getPropertyList(App::PropertyData::OffsetBase offsetBase, std::vector<Property *> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L131{getPropertyList}]]]
+getPropertyMap(App::PropertyData::OffsetBase offsetBase, std::map<std::string,Property *> & Map) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L130{getPropertyMap}]]]
+getPropertyNamedList(App::PropertyData::OffsetBase offsetBase, std::vector<std::pair<const char *,Property *>> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L132{getPropertyNamedList}]]]
+getType(App::PropertyData::OffsetBase offsetBase, const App::Property * prop) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L122{getType}]]]
+getType(App::PropertyData::OffsetBase offsetBase, const char * name) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L123{getType}]]]
+merge(App::PropertyData * other = nullptr) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L134{merge}]]]
+split(App::PropertyData * other) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L135{split}]]]
__
+parentMerged : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L112{parentMerged}]]]
+parentPropertyData : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L114{parentPropertyData}]]]
+propertyData : bmi::multi_index_container<PropertySpec,bmi::indexed_by<bmi::sequenced<>,bmi::hashed_unique<bmi::member<PropertySpec,const char *,&PropertySpec::Name>,CStringHasher,CStringHasher>,bmi::hashed_unique<bmi::member<PropertySpec,short,&PropertySpec::Offset>>>> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L110{propertyData}]]]
}
class "PropertyContainer" as C_0001429340431885784815
class C_0001429340431885784815 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L141{PropertyContainer}]] {
+PropertyContainer() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L151{PropertyContainer}]]]
-PropertyContainer(const App::PropertyContainer &) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L253{PropertyContainer}]]]
+~PropertyContainer() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L157{~PropertyContainer}]]]
..
-operator=(const App::PropertyContainer &) : App::PropertyContainer & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L254{operator=}]]]
..
+Restore(Base::XMLReader & reader) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L222{Restore}]]]
+Save(Base::Writer & writer) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L221{Save}]]]
+addDynamicProperty(const char * type, const char * name = nullptr, const char * group = nullptr, const char * doc = nullptr, short attr = 0, bool ro = false, bool hidden = false) : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L196{addDynamicProperty}]]]
+changeDynamicProperty(const App::Property * prop, const char * group, const char * doc) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L205{changeDynamicProperty}]]]
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L144{create}]]]
+editProperty(const char *) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L224{editProperty}]]]
{static} +getClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L144{getClassTypeId}]]]
+getDynamicPropertyByName(const char * name) const : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L215{getDynamicPropertyByName}]]]
+getDynamicPropertyData(const App::Property * prop) const : DynamicProperty::PropData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L201{getDynamicPropertyData}]]]
+getDynamicPropertyNames() const : std::vector<std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L212{getDynamicPropertyNames}]]]
+getFullName() const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L161{getFullName}]]]
+getMemSize() const : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L159{getMemSize}]]]
+getPropertyByName(const char * name) const : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L164{getPropertyByName}]]]
#getPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L246{getPropertyData}]]]
{static} #getPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L245{getPropertyDataPtr}]]]
+getPropertyDocumentation(const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L185{getPropertyDocumentation}]]]
+getPropertyDocumentation(const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L187{getPropertyDocumentation}]]]
+getPropertyGroup(const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L181{getPropertyGroup}]]]
+getPropertyGroup(const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L183{getPropertyGroup}]]]
+getPropertyList(std::vector<Property *> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L170{getPropertyList}]]]
+getPropertyMap(std::map<std::string,Property *> & Map) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L168{getPropertyMap}]]]
+getPropertyName(const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L166{getPropertyName}]]]
+getPropertyNamedList(std::vector<std::pair<const char *,Property *>> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L172{getPropertyNamedList}]]]
+getPropertyPrefix() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L226{getPropertyPrefix}]]]
+getPropertyType(const char * name) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L179{getPropertyType}]]]
+getPropertyType(const App::Property * prop) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L177{getPropertyType}]]]
+getTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L144{getTypeId}]]]
#handleChangedPropertyName(Base::XMLReader & reader, const char * TypeName, const char * PropName) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L248{handleChangedPropertyName}]]]
#handleChangedPropertyType(Base::XMLReader & reader, const char * TypeName, App::Property * prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L249{handleChangedPropertyType}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L144{init}]]]
+isHidden(const char * name) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L195{isHidden}]]]
+isHidden(const App::Property * prop) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L193{isHidden}]]]
+isReadOnly(const char * name) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L191{isReadOnly}]]]
+isReadOnly(const App::Property * prop) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L189{isReadOnly}]]]
#onBeforeChange(const App::Property *) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L242{onBeforeChange}]]]
#onChanged(const App::Property *) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L240{onChanged}]]]
+onPropertyStatusChanged(const App::Property & prop, unsigned long oldStatus) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L219{onPropertyStatusChanged}]]]
+removeDynamicProperty(const char * name) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L209{removeDynamicProperty}]]]
+setPropertyPrefix(const char * prefix) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L230{setPropertyPrefix}]]]
+setPropertyStatus(unsigned char bit, bool value) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L174{setPropertyStatus}]]]
__
-_propertyPrefix : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L260{_propertyPrefix}]]]
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L144{classTypeId}]]]
#dynamicProps : App::DynamicProperty [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L257{dynamicProps}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/PropertyContainer.h#L261{propertyData}]]]
}
abstract "Property" as C_0001336913775586369336
abstract C_0001336913775586369336 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L54{Property}]] {
+Property() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L103{Property}]]]
-Property(const App::Property &) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L291{Property}]]]
+~Property() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L104{~Property}]]]
..
-operator=(const App::Property &) : App::Property & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L292{operator=}]]]
..
{abstract} +Copy() const = 0 : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L242{Copy}]]]
{abstract} +Paste(const App::Property & from) = 0 : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L244{Paste}]]]
+aboutToSetChildValue(App::Property &) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L249{aboutToSetChildValue}]]]
#aboutToSetValue() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L284{aboutToSetValue}]]]
+afterRestore() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L192{afterRestore}]]]
+canonicalPath(const App::ObjectIdentifier & p) const : App::ObjectIdentifier [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L167{canonicalPath}]]]
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L56{create}]]]
{static} +destroy(App::Property * p) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L107{destroy}]]]
{static} +getClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L56{getClassTypeId}]]]
+getContainer() const : App::PropertyContainer * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L153{getContainer}]]]
+getDocumentation() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L147{getDocumentation}]]]
+getEditorName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L138{getEditorName}]]]
+getFullName() const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L135{getFullName}]]]
+getGroup() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L144{getGroup}]]]
+getID() const : int64_t [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L262{getID}]]]
+getMemSize() const : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L115{getMemSize}]]]
+getName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L124{getName}]]]
+getPathValue(const App::ObjectIdentifier & path) const : const boost::any [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L159{getPathValue}]]]
+getPaths(std::vector<App::ObjectIdentifier> & paths) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L170{getPaths}]]]
+getPyPathValue(const App::ObjectIdentifier &, Py::Object &) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L162{getPyPathValue}]]]
+getStatus() const : unsigned long [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L217{getStatus}]]]
+getType() const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L141{getType}]]]
+getTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L56{getTypeId}]]]
+hasName() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L128{hasName}]]]
+hasSetChildValue(App::Property &) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L247{hasSetChildValue}]]]
#hasSetValue() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L282{hasSetValue}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L56{init}]]]
+isReadOnly() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L227{isReadOnly}]]]
+isSame(const App::Property & other) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L252{isSame}]]]
+isSinglePrecision() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L236{isSinglePrecision}]]]
+isTouched() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L209{isTouched}]]]
{static} +isValidName(const char * name) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L133{isValidName}]]]
+onContainerRestored() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L201{onContainerRestored}]]]
+purgeTouched() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L213{purgeTouched}]]]
+setContainer(App::PropertyContainer * Father) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L150{setContainer}]]]
+setPathValue(const App::ObjectIdentifier & path, const boost::any & value) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L156{setPathValue}]]]
+setReadOnly(bool readOnly) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L226{setReadOnly}]]]
+setSinglePrecision(bool single) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L232{setSinglePrecision}]]]
+setStatus(App::Property::Status pos, bool on) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L223{setStatus}]]]
+setStatusValue(unsigned long status) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L224{setStatusValue}]]]
-syncType(unsigned int type) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L295{syncType}]]]
+testStatus(App::Property::Status pos) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L220{testStatus}]]]
+touch() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L207{touch}]]]
#verifyPath(const App::ObjectIdentifier & p) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L287{verifyPath}]]]
__
#StatusBits : std::bitset<32> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L278{StatusBits}]]]
-_id : int64_t [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L300{_id}]]]
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L56{classTypeId}]]]
-father : App::PropertyContainer * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L298{father}]]]
-myName : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L299{myName}]]]
+signalChanged : boost::signals2::signal<void (const App::Property &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Property.h#L303{signalChanged}]]]
}
class "Document" as C_0002004200455966833299
class C_0002004200455966833299 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L53{Document}]] {
#Document(const char * documentName = "") : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L511{Document}]]]
+~Document() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L507{~Document}]]]
..
+Restore(Base::XMLReader & reader) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L232{Restore}]]]
+Save(Base::Writer & writer) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L231{Save}]]]
#_abortTransaction() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L553{_abortTransaction}]]]
#_addObject(App::DocumentObject * pcObject, const char * pObjectName) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L514{_addObject}]]]
#_checkTransaction(App::DocumentObject * pcDelObj, const App::Property * What, int line) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L516{_checkTransaction}]]]
#_clearRedos() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L531{_clearRedos}]]]
#_commitTransaction(bool notify = false) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L551{_commitTransaction}]]]
#_openTransaction(const char * name = nullptr, int id = 0) : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L549{_openTransaction}]]]
#_rebuildDependencyList(const std::vector<App::DocumentObject *> & objs = std::vector<App::DocumentObject*>()) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L534{_rebuildDependencyList}]]]
#_recomputeFeature(App::DocumentObject * Feat) : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L530{_recomputeFeature}]]]
#_removeObject(App::DocumentObject * pcObject) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L513{_removeObject}]]]
+abortTransaction() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L388{abortTransaction}]]]
+addObject(const char * sType, const char * pObjectName = nullptr, bool isNew = true, const char * viewType = nullptr, bool isPartial = false) : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L247{addObject}]]]
+addObject(App::DocumentObject *, const char * pObjectName = nullptr) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L265{addObject}]]]
+addObjects(const char * sType, const std::vector<std::string> & objectNames, bool isNew = true) : std::vector<DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L255{addObjects}]]]
+addOrRemovePropertyOfObject(App::TransactionalObject *, App::Property * prop, bool add) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L421{addOrRemovePropertyOfObject}]]]
+addRecomputeObject(App::DocumentObject * obj) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L485{addRecomputeObject}]]]
+afterRestore(bool checkPartial = false) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L190{afterRestore}]]]
+afterRestore(const std::vector<App::DocumentObject *> &, bool checkPartial = false) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L191{afterRestore}]]]
#breakDependency(App::DocumentObject * pcObject, bool clear) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L517{breakDependency}]]]
+checkOnCycle() : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L429{checkOnCycle}]]]
+clearDocument() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L177{clearDocument}]]]
+clearUndos() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L405{clearUndos}]]]
+commitTransaction() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L386{commitTransaction}]]]
+copyObject(const std::vector<DocumentObject *> & objs, bool recursive = false, bool returnAll = false) : std::vector<DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L279{copyObject}]]]
+countObjects() const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L315{countObjects}]]]
+countObjectsOfType(const Base::Type & typeId) const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L313{countObjectsOfType}]]]
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L55{create}]]]
+exportGraphviz(std::ostream &) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L198{exportGraphviz}]]]
+exportObjects(const std::vector<App::DocumentObject *> &, std::ostream &) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L197{exportObjects}]]]
+findObjects(const Base::Type & typeId, const char * objname, const char * label) const : std::vector<DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L310{findObjects}]]]
+getActiveObject() const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L290{getActiveObject}]]]
+getAvailableRedoNames() const : std::vector<std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L415{getAvailableRedoNames}]]]
+getAvailableRedos(int id = 0) const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L413{getAvailableRedos}]]]
+getAvailableUndoNames() const : std::vector<std::string> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L409{getAvailableUndoNames}]]]
+getAvailableUndos(int id = 0) const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L407{getAvailableUndos}]]]
{static} +getClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L55{getClassTypeId}]]]
{static} +getDependencyList(const std::vector<App::DocumentObject *> & objs, int options = 0) : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L451{getDependencyList}]]]
+getDependentDocuments(bool sort = true) : std::vector<App::Document *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L454{getDependentDocuments}]]]
{static} +getDependentDocuments(std::vector<App::Document *> docs, bool sort) : std::vector<App::Document *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L455{getDependentDocuments}]]]
+getDependingObjects() const : std::vector<DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L304{getDependingObjects}]]]
+getErrorDescription(const App::DocumentObject *) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L343{getErrorDescription}]]]
+getFileName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L228{getFileName}]]]
+getFullName() const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L494{getFullName}]]]
+getInList(const App::DocumentObject * me) const : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L431{getInList}]]]
+getLinksTo(std::set<DocumentObject *> & links, const App::DocumentObject * obj, int options, int maxCount = 0, const std::vector<DocumentObject *> & objs = = {}) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L477{getLinksTo}]]]
+getMaxUndoStackSize() const : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L403{getMaxUndoStackSize}]]]
+getMemSize() const : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L235{getMemSize}]]]
+getName() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L219{getName}]]]
+getObject(const char * Name) const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L292{getObject}]]]
+getObjectByID(long id) const : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L294{getObjectByID}]]]
+getObjectName(App::DocumentObject * pFeat) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L298{getObjectName}]]]
+getObjects() const : const std::vector<DocumentObject *> & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L306{getObjects}]]]
+getObjectsOfType<T>() const : std::vector<T *>
+getObjectsOfType(const Base::Type & typeId) const : std::vector<DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L307{getObjectsOfType}]]]
+getObjectsWithExtension(const Base::Type & typeId, bool derived = true) const : std::vector<DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L309{getObjectsWithExtension}]]]
+getOldLabel() const : const std::string & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L487{getOldLabel}]]]
+getPathsByOutList(const App::DocumentObject * from, const App::DocumentObject * to) const : std::vector<std::list<App::DocumentObject *>> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L464{getPathsByOutList}]]]
+getProgramVersion() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L221{getProgramVersion}]]]
#getPropertyData() const : const App::PropertyData & [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L55{getPropertyData}]]]
{static} #getPropertyDataPtr() : const App::PropertyData * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L55{getPropertyDataPtr}]]]
+getPyObject() : PyObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L492{getPyObject}]]]
+getRootObjects() const : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L462{getRootObjects}]]]
+getStandardObjectName(const char * Name, int d) const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L302{getStandardObjectName}]]]
+getTouched() const : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L328{getTouched}]]]
+getTransactionID(bool undo, unsigned int pos = 0) const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L392{getTransactionID}]]]
#getTransientDirectoryName(const std::string & uuid, const std::string & filename) const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L537{getTransientDirectoryName}]]]
+getTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L55{getTypeId}]]]
+getUndoMemSize() const : unsigned int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L399{getUndoMemSize}]]]
+getUndoMode() const : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L371{getUndoMode}]]]
+getUniqueObjectName(const char * Name) const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L300{getUniqueObjectName}]]]
+hasLinksTo(const App::DocumentObject * obj) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L482{hasLinksTo}]]]
+hasPendingTransaction() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L390{hasPendingTransaction}]]]
+importLinks(const std::vector<App::DocumentObject *> & objs = = {}) : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L212{importLinks}]]]
+importObjects(Base::XMLReader & reader) : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L199{importObjects}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L55{init}]]]
{static} +isAnyRestoring() : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L497{isAnyRestoring}]]]
+isClosable() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L332{isClosable}]]]
+isExporting(const App::DocumentObject * obj) const : App::Document::ExportStatus [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L196{isExporting}]]]
+isIn(const App::DocumentObject * pFeat) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L296{isIn}]]]
+isPerformingTransaction() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L419{isPerformingTransaction}]]]
+isSaved() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L217{isSaved}]]]
+isTouched() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L324{isTouched}]]]
+isTransactionEmpty() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L395{isTransactionEmpty}]]]
+moveObject(App::DocumentObject * obj, bool recursive = false) : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L288{moveObject}]]]
+mustExecute() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L326{mustExecute}]]]
#onBeforeChange(const App::Property * prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L522{onBeforeChange}]]]
#onBeforeChangeProperty(const App::TransactionalObject * Who, const App::Property * What) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L525{onBeforeChangeProperty}]]]
#onChanged(const App::Property * prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L523{onChanged}]]]
#onChangedProperty(const App::DocumentObject * Who, const App::Property * What) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L527{onChangedProperty}]]]
+openTransaction(const char * name = nullptr) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L382{openTransaction}]]]
+purgeTouched() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L322{purgeTouched}]]]
#readObjects(Base::XMLReader & reader) : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L518{readObjects}]]]
+recompute(const std::vector<App::DocumentObject *> & objs = ={}, bool force = false, bool * hasError = nullptr, int options = 0) : int [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L338{recompute}]]]
+recomputeFeature(App::DocumentObject * Feat, bool recursive = false) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L341{recomputeFeature}]]]
+redo(int id = 0) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L417{redo}]]]
+removeObject(const char * sName) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L257{removeObject}]]]
+renameObjectIdentifiers(const std::map<App::ObjectIdentifier,App::ObjectIdentifier> & paths, const std::function<bool (const App::DocumentObject *)> & selector = [](const App::DocumentObject *) { return true; }) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L490{renameObjectIdentifiers}]]]
+renameTransaction(const char * name, int id) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L384{renameTransaction}]]]
+restore(const char * filename = nullptr, bool delaySignal = false, const std::vector<std::string> & objNames = ={}) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L188{restore}]]]
+save() : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L184{save}]]]
+saveAs(const char * file) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L185{saveAs}]]]
+saveCopy(const char * file) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L186{saveCopy}]]]
#saveToFile(const char * filename) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L520{saveToFile}]]]
+setClosable(bool) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L330{setClosable}]]]
+setMaxUndoStackSize(unsigned int UndoMaxStackSize = 20) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L401{setMaxUndoStackSize}]]]
+setStatus(App::Document::Status pos, bool on) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L347{setStatus}]]]
+setTransactionMode(int iMode) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L373{setTransactionMode}]]]
+setUndoLimit(unsigned int UndoMemSize = 0) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L397{setUndoLimit}]]]
+setUndoMode(int iMode) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L369{setUndoMode}]]]
+testStatus(App::Document::Status pos) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L345{testStatus}]]]
+topologicalSort() const : std::vector<App::DocumentObject *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L460{topologicalSort}]]]
+undo(int id = 0) : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L411{undo}]]]
+writeDependencyGraphViz(std::ostream & out) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L427{writeDependencyGraphViz}]]]
#writeObjects(const std::vector<App::DocumentObject *> &, Base::Writer & writer) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L519{writeObjects}]]]
__
+Comment : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L89{Comment}]]]
+Company : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L87{Company}]]]
+CreatedBy : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L81{CreatedBy}]]]
+CreationDate : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L82{CreationDate}]]]
+FileName : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L79{FileName}]]]
+Id : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L91{Id}]]]
+Label : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L77{Label}]]]
+LastModifiedBy : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L84{LastModifiedBy}]]]
+LastModifiedDate : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L85{LastModifiedDate}]]]
+License : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L95{License}]]]
+LicenseURL : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L97{LicenseURL}]]]
+Material : App::PropertyMap [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L101{Material}]]]
+Meta : App::PropertyMap [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L99{Meta}]]]
+ShowHidden : App::PropertyBool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L109{ShowHidden}]]]
+Tip : App::PropertyLink [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L105{Tip}]]]
+TipName : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L107{TipName}]]]
+TransientDir : App::PropertyString [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L103{TransientDir}]]]
+Uid : App::PropertyUUID [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L93{Uid}]]]
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L55{classTypeId}]]]
-d : struct DocumentP * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L562{d}]]]
-mRedoMap : std::map<int,Transaction *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L560{mRedoMap}]]]
-mRedoTransactions : std::list<Transaction *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L559{mRedoTransactions}]]]
-mUndoMap : std::map<int,Transaction *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L558{mUndoMap}]]]
-mUndoTransactions : std::list<Transaction *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L557{mUndoTransactions}]]]
-myName : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L565{myName}]]]
-oldLabel : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L564{oldLabel}]]]
{static} -propertyData : App::PropertyData [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L55{propertyData}]]]
+signalAbortTransaction : boost::signals2::signal<void (const App::Document &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L169{signalAbortTransaction}]]]
+signalActivatedObject : boost::signals2::signal<void (const App::DocumentObject &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L132{signalActivatedObject}]]]
+signalBeforeChange : boost::signals2::signal<void (const App::Document &,const App::Property &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L115{signalBeforeChange}]]]
+signalBeforeChangeObject : boost::signals2::signal<void (const App::DocumentObject &,const App::Property &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L124{signalBeforeChangeObject}]]]
+signalBeforeRecompute : boost::signals2::signal<void (const App::Document &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L161{signalBeforeRecompute}]]]
+signalChangePropertyEditor : boost::signals2::signal<void (const App::Document &,const App::Property &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L172{signalChangePropertyEditor}]]]
+signalChanged : boost::signals2::signal<void (const App::Document &,const App::Property &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L117{signalChanged}]]]
+signalChangedObject : boost::signals2::signal<void (const App::DocumentObject &,const App::Property &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L126{signalChangedObject}]]]
+signalCommitTransaction : boost::signals2::signal<void (const App::Document &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L167{signalCommitTransaction}]]]
+signalDeletedObject : boost::signals2::signal<void (const App::DocumentObject &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L122{signalDeletedObject}]]]
+signalExportObjects : boost::signals2::signal<void (const std::vector<App::DocumentObject *> &,Base::Writer &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L149{signalExportObjects}]]]
+signalExportViewObjects : boost::signals2::signal<void (const std::vector<App::DocumentObject *> &,Base::Writer &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L151{signalExportViewObjects}]]]
+signalFinishImportObjects : boost::signals2::signal<void (const std::vector<App::DocumentObject *> &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L156{signalFinishImportObjects}]]]
+signalFinishRestoreObject : boost::signals2::signal<void (const App::DocumentObject &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L171{signalFinishRestoreObject}]]]
+signalFinishSave : boost::signals2::signal<void (const App::Document &,const std::string &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L160{signalFinishSave}]]]
+signalImportObjects : boost::signals2::signal<void (const std::vector<App::DocumentObject *> &,Base::XMLReader &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L153{signalImportObjects}]]]
+signalImportViewObjects : boost::signals2::signal<void (const std::vector<App::DocumentObject *> &,Base::Reader &,const std::map<std::string,std::string> &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L155{signalImportViewObjects}]]]
+signalLinkXsetValue : boost::signals2::signal<void (std::string)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L174{signalLinkXsetValue}]]]
+signalNewObject : boost::signals2::signal<void (const App::DocumentObject &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L119{signalNewObject}]]]
+signalOpenTransaction : boost::signals2::signal<void (const App::Document &,std::string)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L165{signalOpenTransaction}]]]
+signalRecomputed : boost::signals2::signal<void (const App::Document &,const std::vector<App::DocumentObject *> &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L162{signalRecomputed}]]]
+signalRecomputedObject : boost::signals2::signal<void (const App::DocumentObject &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L163{signalRecomputedObject}]]]
+signalRedo : boost::signals2::signal<void (const App::Document &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L140{signalRedo}]]]
+signalRelabelObject : boost::signals2::signal<void (const App::DocumentObject &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L130{signalRelabelObject}]]]
+signalRestoreDocument : boost::signals2::signal<void (Base::XMLReader &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L147{signalRestoreDocument}]]]
+signalSaveDocument : boost::signals2::signal<void (Base::Writer &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L146{signalSaveDocument}]]]
+signalSkipRecompute : boost::signals2::signal<void (const App::Document &,const std::vector<App::DocumentObject *> &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L170{signalSkipRecompute}]]]
+signalStartSave : boost::signals2::signal<void (const App::Document &,const std::string &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L158{signalStartSave}]]]
+signalTouchedObject : boost::signals2::signal<void (const App::DocumentObject &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L128{signalTouchedObject}]]]
+signalTransactionAppend : boost::signals2::signal<void (const App::DocumentObject &,Transaction *)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L134{signalTransactionAppend}]]]
+signalTransactionRemove : boost::signals2::signal<void (const App::DocumentObject &,Transaction *)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L136{signalTransactionRemove}]]]
+signalUndo : boost::signals2::signal<void (const App::Document &)> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/Document.h#L138{signalUndo}]]]
}
class "ExtensionContainer" as C_0000679410891240475874
class C_0000679410891240475874 [[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L110{ExtensionContainer}]] {
+ExtensionContainer() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L119{ExtensionContainer}]]]
+~ExtensionContainer() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L120{~ExtensionContainer}]]]
..
+Restore(Base::XMLReader & reader) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L179{Restore}]]]
+Save(Base::Writer & writer) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L178{Save}]]]
{static} +create() : void * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L113{create}]]]
+extensionBegin() : App::ExtensionContainer::ExtensionIterator [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L147{extensionBegin}]]]
+extensionEnd() : App::ExtensionContainer::ExtensionIterator [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L148{extensionEnd}]]]
{static} +getClassTypeId() : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L113{getClassTypeId}]]]
+getExtension(Base::Type, bool derived = true, bool no_except = false) const : App::Extension * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L126{getExtension}]]]
+getExtension(const std::string & name) const : App::Extension * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L127{getExtension}]]]
+getExtensionByType<ExtensionT>(bool no_except = false, bool derived = true) const : ExtensionT *
+getExtensionsDerivedFrom(Base::Type type) const : std::vector<Extension *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L136{getExtensionsDerivedFrom}]]]
+getExtensionsDerivedFromType<ExtensionT>() const : std::vector<ExtensionT *>
+getPropertyByName(const char * name) const : App::Property * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L154{getPropertyByName}]]]
+getPropertyDocumentation(const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L171{getPropertyDocumentation}]]]
+getPropertyDocumentation(const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L173{getPropertyDocumentation}]]]
+getPropertyGroup(const char * name) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L169{getPropertyGroup}]]]
+getPropertyGroup(const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L167{getPropertyGroup}]]]
+getPropertyList(std::vector<Property *> & List) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L160{getPropertyList}]]]
+getPropertyMap(std::map<std::string,Property *> & Map) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L158{getPropertyMap}]]]
+getPropertyName(const App::Property * prop) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L156{getPropertyName}]]]
+getPropertyType(const App::Property * prop) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L163{getPropertyType}]]]
+getPropertyType(const char * name) const : short [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L165{getPropertyType}]]]
+getTypeId() const : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L113{getTypeId}]]]
+handleChangedPropertyName(Base::XMLReader & reader, const char * TypeName, const char * PropName) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L193{handleChangedPropertyName}]]]
+handleChangedPropertyType(Base::XMLReader & reader, const char * TypeName, App::Property * prop) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L201{handleChangedPropertyType}]]]
+hasExtension(const std::string & name) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L124{hasExtension}]]]
+hasExtension(Base::Type, bool derived = true) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L123{hasExtension}]]]
+hasExtensions() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L125{hasExtensions}]]]
{static} +init() : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L113{init}]]]
+onChanged(const App::Property *) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L176{onChanged}]]]
+registerExtension(Base::Type extension, App::Extension * ext) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L122{registerExtension}]]]
+restoreExtensions(Base::XMLReader & reader) : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L184{restoreExtensions}]]]
+saveExtensions(Base::Writer & writer) const : void [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L183{saveExtensions}]]]
__
-_extensions : std::map<Base::Type,App::Extension *> [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L205{_extensions}]]]
{static} -classTypeId : Base::Type [[[https://github.com/FreeCAD/FreeCAD/blob/f6708547a9bb3f71a4aaade12109f511a72c207c/src/App/ExtensionContainer.h#L113{classTypeId}]]]
}
package [ExpressionParser] as C_0000905861183269213715 {
}
package [Meta] as C_0002283864520314866053 {
}
}
C_0001441097518118859586 --> C_0001299587473968259399 : -classTypeId
C_0001065140174462797402 --> C_0001065140174462797402 : +parentPropertyData
C_0001429340431885784815 o-- C_0000874376245777698770 : #dynamicProps
C_0001429340431885784815 --> C_0001299587473968259399 : -classTypeId
C_0001429340431885784815 --> C_0001065140174462797402 : -propertyData
C_0001429340431885784815 <.. C_0000874376245777698770 : +<<friend>>
C_0001429340431885784815 <.. C_0001336913775586369336 : +<<friend>>
C_0001441097518118859586 <|-- C_0001429340431885784815
C_0001336913775586369336 --> C_0001429340431885784815 : -father
C_0001336913775586369336 --> C_0001299587473968259399 : -classTypeId
C_0001336913775586369336 <.. C_0000874376245777698770 : +<<friend>>
C_0001336913775586369336 <.. C_0001065140174462797402 : +<<friend>>
C_0001336913775586369336 <.. C_0001429340431885784815 : +<<friend>>
C_0001441097518118859586 <|-- C_0001336913775586369336
C_0002004200455966833299 --> C_0001299587473968259399 : -classTypeId
C_0002004200455966833299 --> C_0001065140174462797402 : -propertyData
C_0001429340431885784815 <|-- C_0002004200455966833299
C_0000679410891240475874 --> C_0001299587473968259399 : -classTypeId
C_0001429340431885784815 <|-- C_0000679410891240475874

'Generated with clang-uml, version 0.4.0-14-g26abb71
'LLVM version Ubuntu clang version 15.0.7
@enduml
