@startuml
title Godot Node2D class context
left to right direction
class "Vector2" as C_0000053309527800613276
class C_0000053309527800613276 [[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L39{Vector2}]] {
+Vector2(real_t p_x, real_t p_y) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L152{Vector2}]]]
+Vector2() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L156{Vector2}]]]
..
+operator!=(const Vector2 & p_vec2) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L117{operator!=}]]]
+operator*(const Vector2 & p_v1) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L101{operator*}]]]
+operator*(const real_t & rvalue) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L103{operator*}]]]
+operator*=(const real_t & rvalue) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L104{operator*=}]]]
+operator*=(const Vector2 & rvalue) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L105{operator*=}]]]
+operator+(const Vector2 & p_v) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L97{operator+}]]]
+operator+=(const Vector2 & p_v) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L98{operator+=}]]]
+operator-(const Vector2 & p_v) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L99{operator-}]]]
+operator-() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L114{operator-}]]]
+operator-=(const Vector2 & p_v) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L100{operator-=}]]]
+operator/(const Vector2 & p_v1) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L107{operator/}]]]
+operator/(const real_t & rvalue) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L109{operator/}]]]
+operator/=(const real_t & rvalue) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L111{operator/=}]]]
+operator/=(const Vector2 & rvalue) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L112{operator/=}]]]
+operator<(const Vector2 & p_vec2) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L119{operator<}]]]
+operator<=(const Vector2 & p_vec2) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L121{operator<=}]]]
+operator==(const Vector2 & p_vec2) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L116{operator==}]]]
+operator>(const Vector2 & p_vec2) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L120{operator>}]]]
+operator>=(const Vector2 & p_vec2) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L122{operator>=}]]]
+operator[](int p_idx) const : const real_t & [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L58{operator[]}]]]
+operator[](int p_idx) : real_t & [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L55{operator[]}]]]
..
+abs() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L132{abs}]]]
+angle() const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L124{angle}]]]
+angle_to(const Vector2 & p_vector2) const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L71{angle_to}]]]
+angle_to_point(const Vector2 & p_vector2) const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L72{angle_to_point}]]]
+aspect() const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L148{aspect}]]]
+bounce(const Vector2 & p_normal) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L92{bounce}]]]
+ceil() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L145{ceil}]]]
+clamped(real_t p_len) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L83{clamped}]]]
+cross(const Vector2 & p_other) const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L76{cross}]]]
+cubic_interpolate(const Vector2 & p_b, const Vector2 & p_pre_a, const Vector2 & p_post_b, real_t p_weight) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L88{cubic_interpolate}]]]
+direction_to(const Vector2 & p_to) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L73{direction_to}]]]
+distance_squared_to(const Vector2 & p_vector2) const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L70{distance_squared_to}]]]
+distance_to(const Vector2 & p_vector2) const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L69{distance_to}]]]
+dot(const Vector2 & p_other) const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L75{dot}]]]
+floor() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L144{floor}]]]
+is_equal_approx(const Vector2 & p_v) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L95{is_equal_approx}]]]
+is_normalized() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L64{is_normalized}]]]
+length() const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L66{length}]]]
+length_squared() const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L67{length_squared}]]]
{static} +linear_interpolate(const Vector2 & p_a, const Vector2 & p_b, real_t p_weight) : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L85{linear_interpolate}]]]
+linear_interpolate(const Vector2 & p_to, real_t p_weight) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L86{linear_interpolate}]]]
+move_toward(const Vector2 & p_to, const real_t p_delta) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L89{move_toward}]]]
+normalize() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L62{normalize}]]]
+normalized() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L63{normalized}]]]
+operator String() const : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L150{operator String}]]]
+plane_project(real_t p_d, const Vector2 & p_vec) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L81{plane_project}]]]
+posmod(const real_t p_mod) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L77{posmod}]]]
+posmodv(const Vector2 & p_modv) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L78{posmodv}]]]
+project(const Vector2 & p_to) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L79{project}]]]
+reflect(const Vector2 & p_normal) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L93{reflect}]]]
+rotated(real_t p_by) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L137{rotated}]]]
+round() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L146{round}]]]
+set_rotation(real_t p_radians) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L126{set_rotation}]]]
+sign() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L143{sign}]]]
+slerp(const Vector2 & p_to, real_t p_weight) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L87{slerp}]]]
+slide(const Vector2 & p_normal) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L91{slide}]]]
+snapped(const Vector2 & p_by) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L147{snapped}]]]
+tangent() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L138{tangent}]]]
__
+ : Vector2::(anonymous_506186) [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L46{}]]]
+ : Vector2::(anonymous_506291) [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/vector2.h#L50{}]]]
}
class "Transform2D" as C_0001296138246691404804
class C_0001296138246691404804 [[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L37{Transform2D}]] {
+Transform2D(real_t xx, real_t xy, real_t yx, real_t yy, real_t ox, real_t oy) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L120{Transform2D}]]]
+Transform2D(real_t p_rot, const Vector2 & p_pos) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L130{Transform2D}]]]
+Transform2D() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L131{Transform2D}]]]
..
+operator!=(const Transform2D & p_transform) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L102{operator!=}]]]
+operator*(const Transform2D & p_transform) const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L105{operator*}]]]
+operator*=(const Transform2D & p_transform) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L104{operator*=}]]]
+operator==(const Transform2D & p_transform) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L101{operator==}]]]
+operator[](int p_idx) const : const Vector2 & [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L54{operator[]}]]]
+operator[](int p_idx) : Vector2 & [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L55{operator[]}]]]
..
+affine_inverse() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L70{affine_inverse}]]]
+affine_invert() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L69{affine_invert}]]]
+basis_determinant() const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L82{basis_determinant}]]]
+basis_scaled(const Size2 & p_scale) const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L91{basis_scaled}]]]
+basis_xform(const Vector2 & p_vec) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L109{basis_xform}]]]
+basis_xform_inv(const Vector2 & p_vec) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L110{basis_xform_inv}]]]
+get_axis(int p_axis) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L57{get_axis}]]]
+get_origin() const : const Vector2 & [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L87{get_origin}]]]
+get_rotation() const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L73{get_rotation}]]]
+get_scale() const : Size2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L84{get_scale}]]]
+interpolate_with(const Transform2D & p_transform, real_t p_c) const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L107{interpolate_with}]]]
+inverse() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L67{inverse}]]]
+invert() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L66{invert}]]]
+is_equal_approx(const Transform2D & p_transform) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L99{is_equal_approx}]]]
+operator String() const : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L118{operator String}]]]
+orthonormalize() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L97{orthonormalize}]]]
+orthonormalized() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L98{orthonormalized}]]]
+rotate(real_t p_phi) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L75{rotate}]]]
+rotated(real_t p_phi) const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L93{rotated}]]]
+scale(const Size2 & p_scale) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L77{scale}]]]
+scale_basis(const Size2 & p_scale) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L78{scale_basis}]]]
+scaled(const Size2 & p_scale) const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L90{scaled}]]]
+set_axis(int p_axis, const Vector2 & p_vec) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L61{set_axis}]]]
+set_origin(const Vector2 & p_origin) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L88{set_origin}]]]
+set_rotation(real_t p_rot) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L72{set_rotation}]]]
+set_rotation_and_scale(real_t p_rot, const Size2 & p_scale) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L74{set_rotation_and_scale}]]]
+set_scale(const Size2 & p_scale) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L85{set_scale}]]]
+tdotx(const Vector2 & v) const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L51{tdotx}]]]
+tdoty(const Vector2 & v) const : real_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L52{tdoty}]]]
+translate(real_t p_tx, real_t p_ty) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L79{translate}]]]
+translate(const Vector2 & p_translation) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L80{translate}]]]
+translated(const Vector2 & p_offset) const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L92{translated}]]]
+untranslated() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L95{untranslated}]]]
+xform(const Vector2 & p_vec) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L111{xform}]]]
+xform(const Rect2 & p_rect) const : Rect2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L113{xform}]]]
+xform(const PoolVector<Vector2> & p_array) const : PoolVector<Vector2> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L115{xform}]]]
+xform_inv(const Vector2 & p_vec) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L112{xform_inv}]]]
+xform_inv(const Rect2 & p_rect) const : Rect2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L114{xform_inv}]]]
+xform_inv(const PoolVector<Vector2> & p_array) const : PoolVector<Vector2> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L116{xform_inv}]]]
__
+elements : Vector2[3] [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/math/transform_2d.h#L49{elements}]]]
}
class "StringName" as C_0001858199404643284193
class C_0001858199404643284193 [[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L44{StringName}]] {
-StringName(StringName::_Data * p_data) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L90{StringName}]]]
+StringName(const char * p_name) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L159{StringName}]]]
+StringName(const StringName & p_name) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L160{StringName}]]]
+StringName(const String & p_name) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L161{StringName}]]]
+StringName(const StaticCString & p_static_string) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L162{StringName}]]]
+StringName() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L163{StringName}]]]
+~StringName() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L164{~StringName}]]]
..
+operator=(const StringName & p_name) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L158{operator=}]]]
..
+operator!=(const String & p_name) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L97{operator!=}]]]
+operator!=(const StringName & p_name) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L117{operator!=}]]]
+operator<(const StringName & p_name) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L98{operator<}]]]
+operator==(const String & p_name) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L95{operator==}]]]
+operator==(const char * p_name) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L96{operator==}]]]
+operator==(const StringName & p_name) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L102{operator==}]]]
..
{static} -cleanup() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L87{cleanup}]]]
+data_unique_pointer() const : const void * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L114{data_unique_pointer}]]]
+hash() const : uint32_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L107{hash}]]]
+operator String() const : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L119{operator String}]]]
+operator const void *() const : const void * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L93{operator const void *}]]]
{static} +search(const char * p_name) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L131{search}]]]
{static} +search(const CharType * p_name) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L132{search}]]]
{static} +search(const String & p_name) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L133{search}]]]
{static} -setup() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L86{setup}]]]
-unref() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L81{unref}]]]
__
-STRING_TABLE_BITS : enum
-STRING_TABLE_LEN : enum
-STRING_TABLE_MASK : enum
-_data : StringName::_Data * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L73{_data}]]]
{static} -_table : StringName::_Data *[4096] [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L71{_table}]]]
{static} -configured : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L88{configured}]]]
{static} -lock : Mutex [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/string_name.h#L85{lock}]]]
}
class "ClassDB" as C_0000104564426296396960
class C_0000104564426296396960 [[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L94{ClassDB}]] {
{static} +_add_class<T>() : void
{static} +_add_class2(const StringName & p_class, const StringName & p_inherits) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L159{_add_class2}]]]
{static} +_create_ptr_func<T>() : class Object *
{static} -_get_parent_class(const StringName & p_class) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L166{_get_parent_class}]]]
{static} -_is_parent_class(const StringName & p_class, const StringName & p_inherits) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L167{_is_parent_class}]]]
{static} +add_compatibility_class(const StringName & p_class, const StringName & p_fallback) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L395{add_compatibility_class}]]]
{static} +add_property(StringName p_class, const PropertyInfo & p_pinfo, const StringName & p_setter, const StringName & p_getter, int p_index = -1) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L354{add_property}]]]
{static} +add_property_group(StringName p_class, const String & p_name, const String & p_prefix = "") : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L353{add_property_group}]]]
{static} +add_resource_base_extension(const StringName & p_extension, const StringName & p_class) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L391{add_resource_base_extension}]]]
{static} +add_signal(StringName p_class, const MethodInfo & p_signal) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L348{add_signal}]]]
{static} +add_virtual_method(const StringName & p_class, const MethodInfo & p_method, bool p_virtual = true) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L371{add_virtual_method}]]]
{static} +bind_integer_constant(const StringName & p_class, const StringName & p_enum, const StringName & p_name, int p_constant) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L374{bind_integer_constant}]]]
{static} +bind_method<N,M>(N p_method_name, M p_method, const Variant & p_def1, const Variant & p_def2) : class MethodBind *
{static} +bind_method<N,M>(N p_method_name, M p_method, const Variant & p_def1) : class MethodBind *
{static} +bind_method<N,M>(N p_method_name, M p_method) : class MethodBind *
{static} +bind_method<N,M>(N p_method_name, M p_method, const Variant & p_def1, const Variant & p_def2, const Variant & p_def3) : class MethodBind *
{static} +bind_method<N,M>(N p_method_name, M p_method, const Variant & p_def1, const Variant & p_def2, const Variant & p_def3, const Variant & p_def4) : class MethodBind *
{static} +bind_method<N,M>(N p_method_name, M p_method, const Variant & p_def1, const Variant & p_def2, const Variant & p_def3, const Variant & p_def4, const Variant & p_def5) : class MethodBind *
{static} +bind_method<N,M>(N p_method_name, M p_method, const Variant & p_def1, const Variant & p_def2, const Variant & p_def3, const Variant & p_def4, const Variant & p_def5, const Variant & p_def6) : class MethodBind *
{static} +bind_method<N,M>(N p_method_name, M p_method, const Variant & p_def1, const Variant & p_def2, const Variant & p_def3, const Variant & p_def4, const Variant & p_def5, const Variant & p_def6, const Variant & p_def7) : class MethodBind *
{static} +bind_method<N,M>(N p_method_name, M p_method, const Variant & p_def1, const Variant & p_def2, const Variant & p_def3, const Variant & p_def4, const Variant & p_def5, const Variant & p_def6, const Variant & p_def7, const Variant & p_def8) : class MethodBind *
{static} +bind_methodfi(uint32_t p_flags, MethodBind * p_bind, const MethodDefinition & method_name, const Variant ** p_defs, int p_defcount) : MethodBind * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L152{bind_methodfi}]]]
{static} +bind_vararg_method<M>(uint32_t p_flags, StringName p_name, M p_method, const MethodInfo & p_info = MethodInfo(), const Vector<Variant> & p_default_args = Vector<Variant>(), bool p_return_nil_is_variant = true) : class MethodBind *
{static} +can_instance(const StringName & p_class) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L228{can_instance}]]]
{static} +class_exists(const StringName & p_class) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L226{class_exists}]]]
{static} +class_get_default_property_value(const StringName & p_class, const StringName & p_property, bool * r_valid = __null) : Variant [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L382{class_get_default_property_value}]]]
{static} +cleanup() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L400{cleanup}]]]
{static} +cleanup_defaults() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L399{cleanup_defaults}]]]
{static} +creator<T>() : class Object *
{static} +get_api_hash(ClassDB::APIType p_api) : uint64_t [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L232{get_api_hash}]]]
{static} +get_api_type(const StringName & p_class) : ClassDB::APIType [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L230{get_api_type}]]]
{static} +get_category(const StringName & p_node) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L384{get_category}]]]
{static} +get_class_list(List<StringName> * p_classes) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L221{get_class_list}]]]
{static} +get_current_api() : ClassDB::APIType [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L398{get_current_api}]]]
{static} +get_direct_inheriters_from_class(const StringName & p_class, List<StringName> * p_classes) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L223{get_direct_inheriters_from_class}]]]
{static} +get_enum_constants(const StringName & p_class, const StringName & p_enum, List<StringName> * p_constants, bool p_no_inheritance = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L380{get_enum_constants}]]]
{static} +get_enum_list(const StringName & p_class, List<StringName> * p_enums, bool p_no_inheritance = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L379{get_enum_list}]]]
{static} +get_extensions_for_type(const StringName & p_class, List<String> * p_extensions) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L393{get_extensions_for_type}]]]
{static} +get_inheriters_from_class(const StringName & p_class, List<StringName> * p_classes) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L222{get_inheriters_from_class}]]]
{static} +get_integer_constant(const StringName & p_class, const StringName & p_name, bool * p_success = __null) : int [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L376{get_integer_constant}]]]
{static} +get_integer_constant_enum(const StringName & p_class, const StringName & p_name, bool p_no_inheritance = false) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L378{get_integer_constant_enum}]]]
{static} +get_integer_constant_list(const StringName & p_class, List<String> * p_constants, bool p_no_inheritance = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L375{get_integer_constant_list}]]]
{static} +get_method(StringName p_class, StringName p_name) : MethodBind * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L369{get_method}]]]
{static} +get_method_list(StringName p_class, List<MethodInfo> * p_methods, bool p_no_inheritance = false, bool p_exclude_from_properties = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L368{get_method_list}]]]
{static} +get_parent_class(const StringName & p_class) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L225{get_parent_class}]]]
{static} +get_parent_class_nocheck(const StringName & p_class) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L224{get_parent_class_nocheck}]]]
{static} +get_property(Object * p_object, const StringName & p_property, Variant & r_value) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L358{get_property}]]]
{static} +get_property_getter(StringName p_class, const StringName & p_property) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L363{get_property_getter}]]]
{static} +get_property_index(const StringName & p_class, const StringName & p_property, bool * r_is_valid = __null) : int [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L360{get_property_index}]]]
{static} +get_property_list(StringName p_class, List<PropertyInfo> * p_list, bool p_no_inheritance = false, const Object * p_validator = __null) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L356{get_property_list}]]]
{static} +get_property_setter(StringName p_class, const StringName & p_property) : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L362{get_property_setter}]]]
{static} +get_property_type(const StringName & p_class, const StringName & p_property, bool * r_is_valid = __null) : Variant::Type [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L361{get_property_type}]]]
{static} +get_resource_base_extensions(List<String> * p_extensions) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L392{get_resource_base_extensions}]]]
{static} +get_signal(StringName p_class, StringName p_signal, MethodInfo * r_signal) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L350{get_signal}]]]
{static} +get_signal_list(StringName p_class, List<MethodInfo> * p_signals, bool p_no_inheritance = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L351{get_signal_list}]]]
{static} +get_virtual_methods(const StringName & p_class, List<MethodInfo> * p_methods, bool p_no_inheritance = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L372{get_virtual_methods}]]]
{static} +has_method(StringName p_class, StringName p_method, bool p_no_inheritance = false) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L365{has_method}]]]
{static} +has_property(const StringName & p_class, const StringName & p_property, bool p_no_inheritance = false) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L359{has_property}]]]
{static} +has_signal(StringName p_class, StringName p_signal) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L349{has_signal}]]]
{static} +instance(const StringName & p_class) : Object * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L229{instance}]]]
{static} +is_class_enabled(StringName p_class) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L387{is_class_enabled}]]]
{static} +is_class_exposed(StringName p_class) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L389{is_class_exposed}]]]
{static} +is_parent_class(const StringName & p_class, const StringName & p_inherits) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L227{is_parent_class}]]]
{static} +register_class<T>() : void
{static} +register_custom_instance_class<T>() : void
{static} +register_virtual_class<T>() : void
{static} +set_class_enabled(StringName p_class, bool p_enable) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L386{set_class_enabled}]]]
{static} +set_current_api(ClassDB::APIType p_api) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L397{set_current_api}]]]
{static} +set_method_flags(StringName p_class, StringName p_method, int p_flags) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L366{set_method_flags}]]]
{static} +set_property(Object * p_object, const StringName & p_property, const Variant & p_value, bool * r_valid = __null) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L357{set_property}]]]
{static} +set_property_default_value(StringName p_class, const StringName & p_name, const Variant & p_default) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L355{set_property_default_value}]]]
__
{static} +classes : HashMap<StringName,ClassDB::ClassInfo> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L147{classes}]]]
{static} +compat_classes : HashMap<StringName,StringName> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L149{compat_classes}]]]
{static} +current_api : ClassDB::APIType [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L157{current_api}]]]
{static} +default_values : HashMap<StringName,HashMap<StringName,Variant>> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L161{default_values}]]]
{static} +default_values_cached : Set<StringName> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L162{default_values_cached}]]]
{static} +lock : RWLock [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L146{lock}]]]
{static} +resource_base_extensions : HashMap<StringName,StringName> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./core/class_db.h#L148{resource_base_extensions}]]]
}
abstract "CanvasItem" as C_0002074383603489565895
abstract C_0002074383603489565895 [[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L165{CanvasItem}]] {
+CanvasItem() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L392{CanvasItem}]]]
+~CanvasItem() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L393{~CanvasItem}]]]
..
-operator=(const CanvasItem & p_rval) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{operator=}]]]
..
{static} #_bind_methods() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L238{_bind_methods}]]]
+_edit_get_minimum_size() const : Size2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L278{_edit_get_minimum_size}]]]
+_edit_get_pivot() const : Point2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L283{_edit_get_pivot}]]]
{abstract} +_edit_get_position() const = 0 : Point2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L263{_edit_get_position}]]]
+_edit_get_rect() const : Rect2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L277{_edit_get_rect}]]]
+_edit_get_rotation() const : float [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L272{_edit_get_rotation}]]]
{abstract} +_edit_get_scale() const = 0 : Size2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L267{_edit_get_scale}]]]
+_edit_get_state() const : Dictionary [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L259{_edit_get_state}]]]
+_edit_get_transform() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L285{_edit_get_transform}]]]
+_edit_is_selected_on_click(const Point2 & p_point, double p_tolerance) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L255{_edit_is_selected_on_click}]]]
+_edit_set_pivot(const Point2 & p_pivot) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L282{_edit_set_pivot}]]]
{abstract} +_edit_set_position(const Point2 & p_position) = 0 : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L262{_edit_set_position}]]]
+_edit_set_rect(const Rect2 & p_rect) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L276{_edit_set_rect}]]]
+_edit_set_rotation(float p_rotation) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L271{_edit_set_rotation}]]]
{abstract} +_edit_set_scale(const Size2 & p_scale) = 0 : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L266{_edit_set_scale}]]]
+_edit_set_state(const Dictionary & p_state) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L258{_edit_set_state}]]]
+_edit_use_pivot() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L281{_edit_use_pivot}]]]
+_edit_use_rect() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L275{_edit_use_rect}]]]
+_edit_use_rotation() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L270{_edit_use_rotation}]]]
-_enter_canvas() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L218{_enter_canvas}]]]
-_exit_canvas() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L219{_exit_canvas}]]]
{static} #_get_bind_methods() : void (*)() [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_get_bind_methods}]]]
+_get_class_namev() const : const StringName * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_get_class_namev}]]]
#_get_get() const : bool (Object::*)(const StringName &,Variant &) const [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_get_get}]]]
#_get_get_property_list() const : void (Object::*)(List<PropertyInfo> *) const [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_get_get_property_list}]]]
#_get_notification() const : void (Object::*)(int) [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_get_notification}]]]
#_get_property_listv(List<PropertyInfo> * p_list, bool p_reversed) const : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_get_property_listv}]]]
#_get_set() const : bool (Object::*)(const StringName &,const Variant &) [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_get_set}]]]
#_getv(const StringName & p_name, Variant & r_ret) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_getv}]]]
#_initialize_classv() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_initialize_classv}]]]
-_is_on_top() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L224{_is_on_top}]]]
#_notification(int p_what) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L237{_notification}]]]
#_notificationv(int p_notification, bool p_reversed) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_notificationv}]]]
-_notify_transform(CanvasItem * p_node) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L221{_notify_transform}]]]
#_notify_transform() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L229{_notify_transform}]]]
-_propagate_visibility_changed(bool p_visible) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L214{_propagate_visibility_changed}]]]
-_set_on_top(bool p_on_top) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L223{_set_on_top}]]]
#_setv(const StringName & p_name, const Variant & p_property) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_setv}]]]
-_toplevel_raise_self() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L212{_toplevel_raise_self}]]]
-_update_callback() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L216{_update_callback}]]]
+draw_arc(const Vector2 & p_center, float p_radius, float p_start_angle, float p_end_angle, int p_point_count, const Color & p_color, float p_width = 1.0, bool p_antialiased = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L312{draw_arc}]]]
+draw_char(const Ref<Font> & p_font, const Point2 & p_pos, const String & p_char, const String & p_next = "", const Color & p_modulate = Color(1, 1, 1)) : float [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L329{draw_char}]]]
+draw_circle(const Point2 & p_pos, float p_radius, const Color & p_color) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L316{draw_circle}]]]
+draw_colored_polygon(const Vector<Point2> & p_points, const Color & p_color, const Vector<Point2> & p_uvs = Vector<Point2>(), Ref<Texture> p_texture = = Ref<Texture>(), const Ref<Texture> & p_normal_map = Ref<Texture>(), bool p_antialiased = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L323{draw_colored_polygon}]]]
+draw_line(const Point2 & p_from, const Point2 & p_to, const Color & p_color, float p_width = 1.0, bool p_antialiased = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L309{draw_line}]]]
+draw_mesh(const Ref<Mesh> & p_mesh, const Ref<Texture> & p_texture, const Ref<Texture> & p_normal_map, const Transform2D & p_transform = Transform2D(), const Color & p_modulate = Color(1, 1, 1)) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L325{draw_mesh}]]]
+draw_multiline(const Vector<Point2> & p_points, const Color & p_color, float p_width = 1.0, bool p_antialiased = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L313{draw_multiline}]]]
+draw_multiline_colors(const Vector<Point2> & p_points, const Vector<Color> & p_colors, float p_width = 1.0, bool p_antialiased = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L314{draw_multiline_colors}]]]
+draw_multimesh(const Ref<MultiMesh> & p_multimesh, const Ref<Texture> & p_texture, const Ref<Texture> & p_normal_map) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L326{draw_multimesh}]]]
+draw_polygon(const Vector<Point2> & p_points, const Vector<Color> & p_colors, const Vector<Point2> & p_uvs = Vector<Point2>(), Ref<Texture> p_texture = = Ref<Texture>(), const Ref<Texture> & p_normal_map = Ref<Texture>(), bool p_antialiased = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L322{draw_polygon}]]]
+draw_polyline(const Vector<Point2> & p_points, const Color & p_color, float p_width = 1.0, bool p_antialiased = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L310{draw_polyline}]]]
+draw_polyline_colors(const Vector<Point2> & p_points, const Vector<Color> & p_colors, float p_width = 1.0, bool p_antialiased = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L311{draw_polyline_colors}]]]
+draw_primitive(const Vector<Point2> & p_points, const Vector<Color> & p_colors, const Vector<Point2> & p_uvs, Ref<Texture> p_texture = = Ref<Texture>(), float p_width = 1, const Ref<Texture> & p_normal_map = Ref<Texture>()) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L321{draw_primitive}]]]
+draw_rect(const Rect2 & p_rect, const Color & p_color, bool p_filled = true, float p_width = 1.0, bool p_antialiased = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L315{draw_rect}]]]
+draw_set_transform(const Point2 & p_offset, float p_rot, const Size2 & p_scale) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L331{draw_set_transform}]]]
+draw_set_transform_matrix(const Transform2D & p_matrix) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L332{draw_set_transform_matrix}]]]
+draw_string(const Ref<Font> & p_font, const Point2 & p_pos, const String & p_text, const Color & p_modulate = Color(1, 1, 1), int p_clip_w = -1) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L328{draw_string}]]]
+draw_style_box(const Ref<StyleBox> & p_style_box, const Rect2 & p_rect) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L320{draw_style_box}]]]
+draw_texture(const Ref<Texture> & p_texture, const Point2 & p_pos, const Color & p_modulate = Color(1, 1, 1, 1), const Ref<Texture> & p_normal_map = Ref<Texture>()) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L317{draw_texture}]]]
+draw_texture_rect(const Ref<Texture> & p_texture, const Rect2 & p_rect, bool p_tile = false, const Color & p_modulate = Color(1, 1, 1), bool p_transpose = false, const Ref<Texture> & p_normal_map = Ref<Texture>()) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L318{draw_texture_rect}]]]
+draw_texture_rect_region(const Ref<Texture> & p_texture, const Rect2 & p_rect, const Rect2 & p_src_rect, const Color & p_modulate = Color(1, 1, 1), bool p_transpose = false, const Ref<Texture> & p_normal_map = Ref<Texture>(), bool p_clip_uv = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L319{draw_texture_rect_region}]]]
+force_update_transform() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L385{force_update_transform}]]]
+get_anchorable_rect() const : Rect2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L388{get_anchorable_rect}]]]
+get_canvas() const : RID [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L363{get_canvas}]]]
+get_canvas_item() const : RID [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L352{get_canvas_item}]]]
+get_canvas_layer() const : int [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L390{get_canvas_layer}]]]
+get_canvas_layer_instance_id() const : ObjectID [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L364{get_canvas_layer_instance_id}]]]
+get_canvas_transform() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L359{get_canvas_transform}]]]
{static} +get_category_static() : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{get_category_static}]]]
+get_class() const : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{get_class}]]]
{static} +get_class_ptr_static() : void * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{get_class_ptr_static}]]]
{static} +get_class_static() : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{get_class_static}]]]
{static} +get_current_item_drawn() : CanvasItem * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L334{get_current_item_drawn}]]]
+get_global_mouse_position() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L376{get_global_mouse_position}]]]
+get_global_transform() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L348{get_global_transform}]]]
+get_global_transform_with_canvas() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L349{get_global_transform_with_canvas}]]]
{static} +get_inheritance_list_static(List<String> * p_inheritance_list) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{get_inheritance_list_static}]]]
+get_light_mask() const : int [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L299{get_light_mask}]]]
+get_local_mouse_position() const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L377{get_local_mouse_position}]]]
+get_material() const : Ref<Material> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L368{get_material}]]]
+get_modulate() const : Color [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L302{get_modulate}]]]
{static} +get_parent_class_static() : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{get_parent_class_static}]]]
+get_parent_item() const : CanvasItem * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L344{get_parent_item}]]]
+get_self_modulate() const : Color [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L305{get_self_modulate}]]]
+get_toplevel() const : CanvasItem * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L351{get_toplevel}]]]
{abstract} +get_transform() const = 0 : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L346{get_transform}]]]
+get_use_parent_material() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L371{get_use_parent_material}]]]
{static} +get_valid_parents_static(List<String> * p_parents) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{get_valid_parents_static}]]]
+get_viewport_rect() const : Rect2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L361{get_viewport_rect}]]]
+get_viewport_rid() const : RID [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L362{get_viewport_rid}]]]
+get_viewport_transform() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L360{get_viewport_transform}]]]
+get_world_2d() const : Ref<World2D> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L365{get_world_2d}]]]
+hide() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L294{hide}]]]
{static} +inherits_static() : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{inherits_static}]]]
{static} +initialize_class() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{initialize_class}]]]
+is_block_transform_notify_enabled() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L357{is_block_transform_notify_enabled}]]]
+is_class(const String & p_class) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{is_class}]]]
+is_class_ptr(void * p_ptr) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{is_class_ptr}]]]
+is_draw_behind_parent_enabled() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L342{is_draw_behind_parent_enabled}]]]
+is_local_transform_notification_enabled() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L380{is_local_transform_notification_enabled}]]]
+is_set_as_toplevel() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L339{is_set_as_toplevel}]]]
+is_transform_notification_enabled() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L383{is_transform_notification_enabled}]]]
+is_visible() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L291{is_visible}]]]
+is_visible_in_tree() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L292{is_visible_in_tree}]]]
#item_rect_changed(bool p_size_changed = true) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L235{item_rect_changed}]]]
+make_canvas_position_local(const Vector2 & screen_point) const : Vector2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L374{make_canvas_position_local}]]]
+make_input_local(const Ref<InputEvent> & p_event) const : Ref<InputEvent> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L373{make_input_local}]]]
+set_as_toplevel(bool p_toplevel) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L338{set_as_toplevel}]]]
+set_block_transform_notify(bool p_enable) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L356{set_block_transform_notify}]]]
+set_draw_behind_parent(bool p_enable) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L341{set_draw_behind_parent}]]]
+set_light_mask(int p_light_mask) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L298{set_light_mask}]]]
+set_material(const Ref<Material> & p_material) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L367{set_material}]]]
+set_modulate(const Color & p_modulate) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L301{set_modulate}]]]
+set_notify_local_transform(bool p_enable) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L379{set_notify_local_transform}]]]
+set_notify_transform(bool p_enable) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L382{set_notify_transform}]]]
+set_self_modulate(const Color & p_self_modulate) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L304{set_self_modulate}]]]
+set_use_parent_material(bool p_use_parent_material) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L370{set_use_parent_material}]]]
+set_visible(bool p_visible) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L290{set_visible}]]]
+show() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L293{show}]]]
+update() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L296{update}]]]
__
-C : List<CanvasItem *>::Element * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L192{C}]]]
+NOTIFICATION_DRAW : enum
+NOTIFICATION_ENTER_CANVAS : enum
+NOTIFICATION_EXIT_CANVAS : enum
+NOTIFICATION_LOCAL_TRANSFORM_CHANGED : enum
+NOTIFICATION_TRANSFORM_CHANGED : enum
+NOTIFICATION_VISIBILITY_CHANGED : enum
+NOTIFICATION_WORLD_2D_CHANGED : enum
-_class_name : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L167{_class_name}]]]
-behind : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L202{behind}]]]
-block_transform_notify : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L201{block_transform_notify}]]]
-canvas_item : RID [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L183{canvas_item}]]]
-canvas_layer : CanvasLayer * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L186{canvas_layer}]]]
-children_items : List<CanvasItem *> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L191{children_items}]]]
{static} -current_item_drawn : CanvasItem * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L226{current_item_drawn}]]]
-drawing : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L200{drawing}]]]
-first_draw : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L196{first_draw}]]]
-global_invalid : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L210{global_invalid}]]]
-global_transform : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L209{global_transform}]]]
-group : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L184{group}]]]
-light_mask : int [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L194{light_mask}]]]
-material : Ref<Material> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L207{material}]]]
-modulate : Color [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L188{modulate}]]]
-notify_local_transform : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L204{notify_local_transform}]]]
-notify_transform : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L205{notify_transform}]]]
-pending_update : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L198{pending_update}]]]
-self_modulate : Color [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L189{self_modulate}]]]
-toplevel : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L199{toplevel}]]]
-use_parent_material : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L203{use_parent_material}]]]
-visible : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L197{visible}]]]
-xform_change : SelfList<Node> [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/./scene/2d/canvas_item.h#L181{xform_change}]]]
}
class "Node2D" as C_0002289363354048605759
class C_0002289363354048605759 [[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L36{Node2D}]] {
+Node2D() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L120{Node2D}]]]
..
-operator=(const Node2D & p_rval) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{operator=}]]]
..
{static} #_bind_methods() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L55{_bind_methods}]]]
+_edit_get_position() const : Point2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L63{_edit_get_position}]]]
+_edit_get_rotation() const : float [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L69{_edit_get_rotation}]]]
+_edit_get_scale() const : Size2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L66{_edit_get_scale}]]]
+_edit_get_state() const : Dictionary [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L59{_edit_get_state}]]]
+_edit_set_position(const Point2 & p_position) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L62{_edit_set_position}]]]
+_edit_set_rect(const Rect2 & p_edit_rect) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L72{_edit_set_rect}]]]
+_edit_set_rotation(float p_rotation) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L68{_edit_set_rotation}]]]
+_edit_set_scale(const Size2 & p_scale) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L65{_edit_set_scale}]]]
+_edit_set_state(const Dictionary & p_state) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L60{_edit_set_state}]]]
+_edit_use_rotation() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L70{_edit_use_rotation}]]]
{static} #_get_bind_methods() : void (*)() [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_get_bind_methods}]]]
+_get_class_namev() const : const StringName * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_get_class_namev}]]]
#_get_get() const : bool (Object::*)(const StringName &,Variant &) const [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_get_get}]]]
#_get_get_property_list() const : void (Object::*)(List<PropertyInfo> *) const [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_get_get_property_list}]]]
#_get_notification() const : void (Object::*)(int) [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_get_notification}]]]
#_get_property_listv(List<PropertyInfo> * p_list, bool p_reversed) const : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_get_property_listv}]]]
#_get_set() const : bool (Object::*)(const StringName &,const Variant &) [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_get_set}]]]
#_getv(const StringName & p_name, Variant & r_ret) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_getv}]]]
#_initialize_classv() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_initialize_classv}]]]
#_notificationv(int p_notification, bool p_reversed) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_notificationv}]]]
#_setv(const StringName & p_name, const Variant & p_property) : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_setv}]]]
-_update_transform() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L50{_update_transform}]]]
-_update_xform_values() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L52{_update_xform_values}]]]
+apply_scale(const Size2 & p_amount) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L85{apply_scale}]]]
+get_angle_to(const Vector2 & p_pos) const : float [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L108{get_angle_to}]]]
{static} +get_category_static() : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{get_category_static}]]]
+get_class() const : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{get_class}]]]
{static} +get_class_ptr_static() : void * [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{get_class_ptr_static}]]]
{static} +get_class_static() : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{get_class_static}]]]
+get_global_position() const : Point2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L92{get_global_position}]]]
+get_global_rotation() const : float [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L93{get_global_rotation}]]]
+get_global_rotation_degrees() const : float [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L94{get_global_rotation_degrees}]]]
+get_global_scale() const : Size2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L95{get_global_scale}]]]
{static} +get_inheritance_list_static(List<String> * p_inheritance_list) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{get_inheritance_list_static}]]]
{static} +get_parent_class_static() : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{get_parent_class_static}]]]
+get_position() const : Point2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L87{get_position}]]]
+get_relative_transform_to_parent(const Node * p_parent) const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L116{get_relative_transform_to_parent}]]]
+get_rotation() const : float [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L88{get_rotation}]]]
+get_rotation_degrees() const : float [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L89{get_rotation_degrees}]]]
+get_scale() const : Size2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L90{get_scale}]]]
+get_transform() const : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L118{get_transform}]]]
{static} +get_valid_parents_static(List<String> * p_parents) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{get_valid_parents_static}]]]
+get_z_index() const : int [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L105{get_z_index}]]]
+global_translate(const Vector2 & p_amount) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L84{global_translate}]]]
{static} +inherits_static() : String [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{inherits_static}]]]
{static} +initialize_class() : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{initialize_class}]]]
+is_class(const String & p_class) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{is_class}]]]
+is_class_ptr(void * p_ptr) const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{is_class_ptr}]]]
+is_z_relative() const : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L114{is_z_relative}]]]
+look_at(const Vector2 & p_pos) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L107{look_at}]]]
+move_x(float p_delta, bool p_scaled = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L81{move_x}]]]
+move_y(float p_delta, bool p_scaled = false) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L82{move_y}]]]
+rotate(float p_radians) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L80{rotate}]]]
+set_global_position(const Point2 & p_pos) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L99{set_global_position}]]]
+set_global_rotation(float p_radians) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L100{set_global_rotation}]]]
+set_global_rotation_degrees(float p_degrees) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L101{set_global_rotation_degrees}]]]
+set_global_scale(const Size2 & p_scale) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L102{set_global_scale}]]]
+set_global_transform(const Transform2D & p_transform) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L98{set_global_transform}]]]
+set_position(const Point2 & p_pos) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L75{set_position}]]]
+set_rotation(float p_radians) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L76{set_rotation}]]]
+set_rotation_degrees(float p_degrees) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L77{set_rotation_degrees}]]]
+set_scale(const Size2 & p_scale) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L78{set_scale}]]]
+set_transform(const Transform2D & p_transform) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L97{set_transform}]]]
+set_z_as_relative(bool p_enabled) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L113{set_z_as_relative}]]]
+set_z_index(int p_z) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L104{set_z_index}]]]
+to_global(Point2 p_local) const : Point2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L111{to_global}]]]
+to_local(Point2 p_global) const : Point2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L110{to_local}]]]
+translate(const Vector2 & p_amount) : void [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L83{translate}]]]
__
-_class_name : StringName [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L38{_class_name}]]]
-_mat : Transform2D [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L46{_mat}]]]
-_scale : Size2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L42{_scale}]]]
-_xform_dirty : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L48{_xform_dirty}]]]
-angle : float [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L41{angle}]]]
-pos : Point2 [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L40{pos}]]]
-z_index : int [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L43{z_index}]]]
-z_relative : bool [[[https://github.com/godotengine/godot/blob/faf3f883d1a25ec8a2b7a31ecc9e3363613b2478/scene/2d/node_2d.h#L44{z_relative}]]]
}
C_0001296138246691404804 o-- C_0000053309527800613276 : +elements
C_0000104564426296396960 --> C_0001858199404643284193 : +classes
C_0000104564426296396960 --> C_0001858199404643284193 : +resource_base_extensions
C_0000104564426296396960 --> C_0001858199404643284193 : +compat_classes
C_0000104564426296396960 --> C_0001858199404643284193 : +default_values
C_0000104564426296396960 --> C_0001858199404643284193 : +default_values_cached
C_0002074383603489565895 o-- C_0001858199404643284193 : -_class_name
C_0002074383603489565895 o-- C_0001296138246691404804 : -global_transform
C_0002074383603489565895 --> C_0002074383603489565895 : -current_item_drawn
C_0002074383603489565895 <.. C_0000104564426296396960 : +<<friend>>
C_0002289363354048605759 o-- C_0001858199404643284193 : -_class_name
C_0002289363354048605759 o-- C_0000053309527800613276 : -pos
C_0002289363354048605759 o-- C_0000053309527800613276 : -_scale
C_0002289363354048605759 o-- C_0001296138246691404804 : -_mat
C_0002289363354048605759 <.. C_0000104564426296396960 : +<<friend>>
C_0002074383603489565895 <|-- C_0002289363354048605759

'Generated with clang-uml, version 0.4.0-9-gc398c6f
'LLVM version Ubuntu clang version 15.0.7
@enduml
