@startuml
title Data::IndexedName context
package [Data] as C_0007944022382666682349 {
class "IndexedName" as C_0000077198310494763102
class C_0000077198310494763102 [[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L55{IndexedName}]] {
+IndexedName(const char * name = nullptr, int _index = 0) : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L67{IndexedName}]]]
+IndexedName(const char * name, const std::vector<const char *> & allowedTypeNames, bool allowOthers = true) : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L96{IndexedName}]]]
+IndexedName(const QByteArray & data) : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L108{IndexedName}]]]
..
+operator!=(const IndexedName & other) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L198{operator!=}]]]
+operator++() : IndexedName & [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L182{operator++}]]]
+operator+=(int offset) : IndexedName & [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L174{operator+=}]]]
+operator--() : IndexedName & [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L190{operator--}]]]
+operator<(const IndexedName & other) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L221{operator<}]]]
+operator==(const IndexedName & other) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L166{operator==}]]]
+operator[](int input) const : char [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L228{operator[]}]]]
..
+appendToStringBuffer(std::string & buffer) const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L133{appendToStringBuffer}]]]
+compare(const IndexedName & other) const : int [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L204{compare}]]]
{static} +fromConst(const char * name, int index) : IndexedName [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L120{fromConst}]]]
+getIndex() const : int [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L241{getIndex}]]]
+getType() const : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L238{getType}]]]
+isNull() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L252{isNull}]]]
+operator bool() const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L256{operator bool}]]]
#set(const char * name, int length = -1, const std::vector<const char *> & allowedNames = = {}, bool allowOthers = true) : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L271{set}]]]
+setIndex(int input) : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L247{setIndex}]]]
+toString() const : std::string [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L147{toString}]]]
__
-index : int [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L278{index}]]]
-type : const char * [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/IndexedName.h#L277{type}]]]
}
class "MappedElement" as C_0005907300236355149255
class C_0005907300236355149255 [[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L41{MappedElement}]] {
+MappedElement() = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L46{MappedElement}]]]
+MappedElement(const IndexedName & idx, MappedName n) : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L48{MappedElement}]]]
+MappedElement(MappedName n, const IndexedName & idx) : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L53{MappedElement}]]]
+MappedElement(const MappedElement & other) = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L60{MappedElement}]]]
+MappedElement(MappedElement && other) noexcept : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L62{MappedElement}]]]
+~MappedElement() = default : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L58{~MappedElement}]]]
..
+operator=(MappedElement && other) noexcept : MappedElement & [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L67{operator=}]]]
+operator=(const MappedElement & other) = default : MappedElement & [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L74{operator=}]]]
..
+operator!=(const MappedElement & other) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L81{operator!=}]]]
+operator<(const MappedElement & other) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L89{operator<}]]]
+operator==(const MappedElement & other) const : bool [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L76{operator==}]]]
__
+index : IndexedName [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L43{index}]]]
+name : MappedName [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L44{name}]]]
}
class "HistoryItem" as C_0014877617629229202398
class C_0014877617629229202398 [[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L102{HistoryItem}]] {
+HistoryItem(App::DocumentObject * obj, const Data::MappedName & name) : void [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L108{HistoryItem}]]]
__
+element : Data::MappedName [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L105{element}]]]
+index : Data::IndexedName [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L106{index}]]]
+intermediates : std::vector<Data::MappedName> [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L107{intermediates}]]]
+obj : App::DocumentObject * [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L103{obj}]]]
+tag : long [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L104{tag}]]]
}
class "ElementMap::MappedChildElements" as C_0004786846721929822972
class C_0004786846721929822972 [[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/ElementMap.h#L178{ElementMap::MappedChildElements}]] {
__
+count : int [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/ElementMap.h#L181{count}]]]
+elementMap : ElementMapPtr [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/ElementMap.h#L184{elementMap}]]]
+indexedName : IndexedName [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/ElementMap.h#L180{indexedName}]]]
+offset : int [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/ElementMap.h#L182{offset}]]]
+postfix : QByteArray [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/ElementMap.h#L185{postfix}]]]
+sids : ElementIDRefs [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/ElementMap.h#L186{sids}]]]
+tag : long [[[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/ElementMap.h#L183{tag}]]]
}
}
C_0005907300236355149255 o-- C_0000077198310494763102 [[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L43{index}]] : +index
C_0014877617629229202398 o-- C_0000077198310494763102 [[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/MappedElement.h#L106{index}]] : +index
C_0004786846721929822972 o-- C_0000077198310494763102 [[https://github.com/FreeCAD/FreeCAD/blob/2fcc5317fe3aee96ca73475986a577719fc78e20/src/App/ElementMap.h#L180{indexedName}]] : +indexedName

'Generated with clang-uml, version 0.6.1
'LLVM version Ubuntu clang version 19.1.1 (1ubuntu1)
@enduml
